import { setupZoneTestEnv } from 'jest-preset-angular/setup-env/zone';

setupZoneTestEnv({
  errorOnUnknownElements: true,
  errorOnUnknownProperties: true,
});

const yo = [
  {
    rxnClass: 'Ligases.',
    rxnClassHierarcy: 'Ligases.',
    ecNumber: '6.-.-.-',
    classLevel: 1,
    metCount: 2,
    totalMetsInRxnClass: 171,
    proteinCount: 2,
    totalProteinsInRxnClass: 448,
    reactionCount: 52,
    totalRxnsInClass: 78,
    hierarchyArray: ['Ligases.'],
    metCountAverage: '2/171',
    proteinCountAverage: '2/448',
    totalReactionAverage: '52/78',
  },
  {
    rxnClass: 'Transferases.',
    rxnClassHierarcy: 'Transferases.',
    ecNumber: '2.-.-.-',
    classLevel: 1,
    metCount: 6,
    totalMetsInRxnClass: 981,
    proteinCount: 3,
    totalProteinsInRxnClass: 4276,
    reactionCount: 28,
    totalRxnsInClass: 599,
    hierarchyArray: ['Transferases.'],
    metCountAverage: '6/981',
    proteinCountAverage: '3/4276',
    totalReactionAverage: '28/599',
  },
  {
    rxnClass: 'Hydrolases.',
    rxnClassHierarcy: 'Hydrolases.',
    ecNumber: '3.-.-.-',
    classLevel: 1,
    metCount: 7,
    totalMetsInRxnClass: 527,
    proteinCount: 1,
    totalProteinsInRxnClass: 2426,
    reactionCount: 26,
    totalRxnsInClass: 321,
    hierarchyArray: ['Hydrolases.'],
    metCountAverage: '7/527',
    proteinCountAverage: '1/2426',
    totalReactionAverage: '26/321',
  },
  {
    rxnClass: 'Lyases.',
    rxnClassHierarcy: 'Lyases.',
    ecNumber: '4.-.-.-',
    classLevel: 1,
    metCount: 1,
    totalMetsInRxnClass: 213,
    proteinCount: 1,
    totalProteinsInRxnClass: 453,
    reactionCount: 4,
    totalRxnsInClass: 108,
    hierarchyArray: ['Lyases.'],
    metCountAverage: '1/213',
    proteinCountAverage: '1/453',
    totalReactionAverage: '4/108',
  },
  {
    rxnClass: 'Oxidoreductases.',
    rxnClassHierarcy: 'Oxidoreductases.',
    ecNumber: '1.-.-.-',
    classLevel: 1,
    metCount: 1,
    totalMetsInRxnClass: 657,
    proteinCount: 0,
    totalProteinsInRxnClass: 1712,
    reactionCount: 1,
    totalRxnsInClass: 429,
    hierarchyArray: ['Oxidoreductases.'],
    metCountAverage: '1/657',
    totalReactionAverage: '1/429',
  },
  {
    rxnClass: 'Forming carbon-oxygen bonds.',
    rxnClassHierarcy: 'Ligases. | Forming carbon-oxygen bonds.',
    ecNumber: '6.1.-.-',
    classLevel: 2,
    metCount: 1,
    totalMetsInRxnClass: 68,
    proteinCount: 0,
    totalProteinsInRxnClass: 192,
    reactionCount: 22,
    totalRxnsInClass: 22,
    hierarchyArray: ['Ligases.', 'Forming carbon-oxygen bonds.'],
    metCountAverage: '1/68',
    totalReactionAverage: '22/22',
  },
  {
    rxnClass: 'Acting on acid anhydrides.',
    rxnClassHierarcy: 'Hydrolases. | Acting on acid anhydrides.',
    ecNumber: '3.6.-.-',
    classLevel: 2,
    metCount: 5,
    totalMetsInRxnClass: 90,
    proteinCount: 0,
    totalProteinsInRxnClass: 916,
    reactionCount: 18,
    totalRxnsInClass: 57,
    hierarchyArray: ['Hydrolases.', 'Acting on acid anhydrides.'],
    metCountAverage: '5/90',
    totalReactionAverage: '18/57',
  },
  {
    rxnClass: 'Transferring phosphorus-containing groups.',
    rxnClassHierarcy:
      'Transferases. | Transferring phosphorus-containing groups.',
    ecNumber: '2.7.-.-',
    classLevel: 2,
    metCount: 4,
    totalMetsInRxnClass: 293,
    proteinCount: 2,
    totalProteinsInRxnClass: 2421,
    reactionCount: 18,
    totalRxnsInClass: 175,
    hierarchyArray: [
      'Transferases.',
      'Transferring phosphorus-containing groups.',
    ],
    metCountAverage: '4/293',
    proteinCountAverage: '2/2421',
    totalReactionAverage: '18/175',
  },
  {
    rxnClass: 'Forming carbon-sulfur bonds.',
    rxnClassHierarcy: 'Ligases. | Forming carbon-sulfur bonds.',
    ecNumber: '6.2.-.-',
    classLevel: 2,
    metCount: 1,
    totalMetsInRxnClass: 38,
    proteinCount: 0,
    totalProteinsInRxnClass: 112,
    reactionCount: 14,
    totalRxnsInClass: 16,
    hierarchyArray: ['Ligases.', 'Forming carbon-sulfur bonds.'],
    metCountAverage: '1/38',
    totalReactionAverage: '14/16',
  },
  {
    rxnClass: 'Forming carbon-nitrogen bonds.',
    rxnClassHierarcy: 'Ligases. | Forming carbon-nitrogen bonds.',
    ecNumber: '6.3.-.-',
    classLevel: 2,
    metCount: 2,
    totalMetsInRxnClass: 76,
    proteinCount: 2,
    totalProteinsInRxnClass: 92,
    reactionCount: 13,
    totalRxnsInClass: 33,
    hierarchyArray: ['Ligases.', 'Forming carbon-nitrogen bonds.'],
    metCountAverage: '2/76',
    proteinCountAverage: '2/92',
    totalReactionAverage: '13/33',
  },
  {
    rxnClass: 'Glycosyltransferases.',
    rxnClassHierarcy: 'Transferases. | Glycosyltransferases.',
    ecNumber: '2.4.-.-',
    classLevel: 2,
    metCount: 5,
    totalMetsInRxnClass: 198,
    proteinCount: 0,
    totalProteinsInRxnClass: 637,
    reactionCount: 5,
    totalRxnsInClass: 124,
    hierarchyArray: ['Transferases.', 'Glycosyltransferases.'],
    metCountAverage: '5/198',
    totalReactionAverage: '5/124',
  },
  {
    rxnClass: 'Acting on ester bonds.',
    rxnClassHierarcy: 'Hydrolases. | Acting on ester bonds.',
    ecNumber: '3.1.-.-',
    classLevel: 2,
    metCount: 3,
    totalMetsInRxnClass: 247,
    proteinCount: 0,
    totalProteinsInRxnClass: 1027,
    reactionCount: 4,
    totalRxnsInClass: 140,
    hierarchyArray: ['Hydrolases.', 'Acting on ester bonds.'],
    metCountAverage: '3/247',
    totalReactionAverage: '4/140',
  },
  {
    rxnClass: 'Acting on carbon-nitrogen bonds, other than peptide bonds.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on carbon-nitrogen bonds, other than peptide bonds.',
    ecNumber: '3.5.-.-',
    classLevel: 2,
    metCount: 3,
    totalMetsInRxnClass: 139,
    proteinCount: 1,
    totalProteinsInRxnClass: 326,
    reactionCount: 3,
    totalRxnsInClass: 65,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on carbon-nitrogen bonds, other than peptide bonds.',
    ],
    metCountAverage: '3/139',
    proteinCountAverage: '1/326',
    totalReactionAverage: '3/65',
  },
  {
    rxnClass: 'Carbon-nitrogen lyases.',
    rxnClassHierarcy: 'Lyases. | Carbon-nitrogen lyases.',
    ecNumber: '4.3.-.-',
    classLevel: 2,
    metCount: 1,
    totalMetsInRxnClass: 28,
    proteinCount: 1,
    totalProteinsInRxnClass: 52,
    reactionCount: 3,
    totalRxnsInClass: 12,
    hierarchyArray: ['Lyases.', 'Carbon-nitrogen lyases.'],
    metCountAverage: '1/28',
    proteinCountAverage: '1/52',
    totalReactionAverage: '3/12',
  },
  {
    rxnClass: 'Forming phosphoric ester bonds.',
    rxnClassHierarcy: 'Ligases. | Forming phosphoric ester bonds.',
    ecNumber: '6.5.-.-',
    classLevel: 2,
    metCount: 2,
    totalMetsInRxnClass: 11,
    proteinCount: 0,
    totalProteinsInRxnClass: 6,
    reactionCount: 3,
    totalRxnsInClass: 3,
    hierarchyArray: ['Ligases.', 'Forming phosphoric ester bonds.'],
    metCountAverage: '2/11',
    totalReactionAverage: '3/3',
  },
  {
    rxnClass: 'Transferring sulfur-containing groups.',
    rxnClassHierarcy: 'Transferases. | Transferring sulfur-containing groups.',
    ecNumber: '2.8.-.-',
    classLevel: 2,
    metCount: 1,
    totalMetsInRxnClass: 84,
    proteinCount: 0,
    totalProteinsInRxnClass: 79,
    reactionCount: 2,
    totalRxnsInClass: 28,
    hierarchyArray: ['Transferases.', 'Transferring sulfur-containing groups.'],
    metCountAverage: '1/84',
    totalReactionAverage: '2/28',
  },
  {
    rxnClass: 'Acting on carbon-sulfur bonds.',
    rxnClassHierarcy: 'Hydrolases. | Acting on carbon-sulfur bonds.',
    ecNumber: '3.13.-.-',
    classLevel: 2,
    metCount: 1,
    totalMetsInRxnClass: 4,
    proteinCount: 0,
    totalProteinsInRxnClass: 8,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: ['Hydrolases.', 'Acting on carbon-sulfur bonds.'],
    metCountAverage: '1/4',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'Acting on other nitrogenous compounds as donors.',
    rxnClassHierarcy:
      'Oxidoreductases. | Acting on other nitrogenous compounds as donors.',
    ecNumber: '1.7.-.-',
    classLevel: 2,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 11,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Oxidoreductases.',
      'Acting on other nitrogenous compounds as donors.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'Acyltransferases.',
    rxnClassHierarcy: 'Transferases. | Acyltransferases.',
    ecNumber: '2.3.-.-',
    classLevel: 2,
    metCount: 1,
    totalMetsInRxnClass: 229,
    proteinCount: 0,
    totalProteinsInRxnClass: 466,
    reactionCount: 1,
    totalRxnsInClass: 107,
    hierarchyArray: ['Transferases.', 'Acyltransferases.'],
    metCountAverage: '1/229',
    totalReactionAverage: '1/107',
  },
  {
    rxnClass: 'Phosphorus-oxygen lyases.',
    rxnClassHierarcy: 'Lyases. | Phosphorus-oxygen lyases.',
    ecNumber: '4.6.-.-',
    classLevel: 2,
    metCount: 1,
    totalMetsInRxnClass: 15,
    proteinCount: 0,
    totalProteinsInRxnClass: 78,
    reactionCount: 1,
    totalRxnsInClass: 5,
    hierarchyArray: ['Lyases.', 'Phosphorus-oxygen lyases.'],
    metCountAverage: '1/15',
    totalReactionAverage: '1/5',
  },
  {
    rxnClass: 'Transferring molybdenum- or tungsten-containing groups.',
    rxnClassHierarcy:
      'Transferases. | Transferring molybdenum- or tungsten-containing groups.',
    ecNumber: '2.10.-.-',
    classLevel: 2,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 7,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Transferring molybdenum- or tungsten-containing groups.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'Transferring one-carbon groups.',
    rxnClassHierarcy: 'Transferases. | Transferring one-carbon groups.',
    ecNumber: '2.1.-.-',
    classLevel: 2,
    metCount: 0,
    totalMetsInRxnClass: 204,
    proteinCount: 1,
    totalProteinsInRxnClass: 412,
    reactionCount: 1,
    totalRxnsInClass: 104,
    hierarchyArray: ['Transferases.', 'Transferring one-carbon groups.'],
    proteinCountAverage: '1/412',
    totalReactionAverage: '1/104',
  },
  {
    rxnClass: 'Ligases forming aminoacyl-tRNA and related compounds.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds.',
    ecNumber: '6.1.1.-',
    classLevel: 3,
    metCount: 1,
    totalMetsInRxnClass: 68,
    proteinCount: 0,
    totalProteinsInRxnClass: 192,
    reactionCount: 22,
    totalRxnsInClass: 22,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
    ],
    metCountAverage: '1/68',
    totalReactionAverage: '22/22',
  },
  {
    rxnClass: 'In phosphorus-containing anhydrides.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on acid anhydrides. | In phosphorus-containing anhydrides.',
    ecNumber: '3.6.1.-',
    classLevel: 3,
    metCount: 5,
    totalMetsInRxnClass: 88,
    proteinCount: 0,
    totalProteinsInRxnClass: 109,
    reactionCount: 17,
    totalRxnsInClass: 54,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on acid anhydrides.',
      'In phosphorus-containing anhydrides.',
    ],
    metCountAverage: '5/88',
    totalReactionAverage: '17/54',
  },
  {
    rxnClass: 'Acid--thiol ligases.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-sulfur bonds. | Acid--thiol ligases.',
    ecNumber: '6.2.1.-',
    classLevel: 3,
    metCount: 1,
    totalMetsInRxnClass: 38,
    proteinCount: 0,
    totalProteinsInRxnClass: 112,
    reactionCount: 14,
    totalRxnsInClass: 16,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-sulfur bonds.',
      'Acid--thiol ligases.',
    ],
    metCountAverage: '1/38',
    totalReactionAverage: '14/16',
  },
  {
    rxnClass: 'Phosphotransferases with a phosphate group as acceptor.',
    rxnClassHierarcy:
      'Transferases. | Transferring phosphorus-containing groups. | Phosphotransferases with a phosphate group as acceptor.',
    ecNumber: '2.7.4.-',
    classLevel: 3,
    metCount: 2,
    totalMetsInRxnClass: 30,
    proteinCount: 2,
    totalProteinsInRxnClass: 78,
    reactionCount: 11,
    totalRxnsInClass: 19,
    hierarchyArray: [
      'Transferases.',
      'Transferring phosphorus-containing groups.',
      'Phosphotransferases with a phosphate group as acceptor.',
    ],
    metCountAverage: '2/30',
    proteinCountAverage: '2/78',
    totalReactionAverage: '11/19',
  },
  {
    rxnClass: 'Other carbon--nitrogen ligases.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-nitrogen bonds. | Other carbon--nitrogen ligases.',
    ecNumber: '6.3.4.-',
    classLevel: 3,
    metCount: 1,
    totalMetsInRxnClass: 39,
    proteinCount: 2,
    totalProteinsInRxnClass: 44,
    reactionCount: 7,
    totalRxnsInClass: 11,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-nitrogen bonds.',
      'Other carbon--nitrogen ligases.',
    ],
    metCountAverage: '1/39',
    proteinCountAverage: '2/44',
    totalReactionAverage: '7/11',
  },
  {
    rxnClass: 'Pentosyltransferases.',
    rxnClassHierarcy:
      'Transferases. | Glycosyltransferases. | Pentosyltransferases.',
    ecNumber: '2.4.2.-',
    classLevel: 3,
    metCount: 5,
    totalMetsInRxnClass: 54,
    proteinCount: 0,
    totalProteinsInRxnClass: 94,
    reactionCount: 5,
    totalRxnsInClass: 24,
    hierarchyArray: [
      'Transferases.',
      'Glycosyltransferases.',
      'Pentosyltransferases.',
    ],
    metCountAverage: '5/54',
    totalReactionAverage: '5/24',
  },
  {
    rxnClass: 'Carbon--nitrogen ligases with glutamine as amido-N-donor.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-nitrogen bonds. | Carbon--nitrogen ligases with glutamine as amido-N-donor.',
    ecNumber: '6.3.5.-',
    classLevel: 3,
    metCount: 2,
    totalMetsInRxnClass: 21,
    proteinCount: 0,
    totalProteinsInRxnClass: 14,
    reactionCount: 3,
    totalRxnsInClass: 6,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-nitrogen bonds.',
      'Carbon--nitrogen ligases with glutamine as amido-N-donor.',
    ],
    metCountAverage: '2/21',
    totalReactionAverage: '3/6',
  },
  {
    rxnClass: 'Forming phosphoric ester bonds.',
    rxnClassHierarcy:
      'Ligases. | Forming phosphoric ester bonds. | Forming phosphoric ester bonds.',
    ecNumber: '6.5.1.-',
    classLevel: 3,
    metCount: 2,
    totalMetsInRxnClass: 11,
    proteinCount: 0,
    totalProteinsInRxnClass: 6,
    reactionCount: 3,
    totalRxnsInClass: 3,
    hierarchyArray: [
      'Ligases.',
      'Forming phosphoric ester bonds.',
      'Forming phosphoric ester bonds.',
    ],
    metCountAverage: '2/11',
    totalReactionAverage: '3/3',
  },
  {
    rxnClass: 'In cyclic amidines.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on carbon-nitrogen bonds, other than peptide bonds. | In cyclic amidines.',
    ecNumber: '3.5.4.-',
    classLevel: 3,
    metCount: 3,
    totalMetsInRxnClass: 33,
    proteinCount: 1,
    totalProteinsInRxnClass: 112,
    reactionCount: 3,
    totalRxnsInClass: 15,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on carbon-nitrogen bonds, other than peptide bonds.',
      'In cyclic amidines.',
    ],
    metCountAverage: '3/33',
    proteinCountAverage: '1/112',
    totalReactionAverage: '3/15',
  },
  {
    rxnClass: 'Lyases acting on amides, amidines, etc.',
    rxnClassHierarcy:
      'Lyases. | Carbon-nitrogen lyases. | Lyases acting on amides, amidines, etc.',
    ecNumber: '4.3.2.-',
    classLevel: 3,
    metCount: 1,
    totalMetsInRxnClass: 17,
    proteinCount: 1,
    totalProteinsInRxnClass: 37,
    reactionCount: 3,
    totalRxnsInClass: 7,
    hierarchyArray: [
      'Lyases.',
      'Carbon-nitrogen lyases.',
      'Lyases acting on amides, amidines, etc.',
    ],
    metCountAverage: '1/17',
    proteinCountAverage: '1/37',
    totalReactionAverage: '3/7',
  },
  {
    rxnClass: 'Phosphotransferases with an alcohol group as acceptor.',
    rxnClassHierarcy:
      'Transferases. | Transferring phosphorus-containing groups. | Phosphotransferases with an alcohol group as acceptor.',
    ecNumber: '2.7.1.-',
    classLevel: 3,
    metCount: 3,
    totalMetsInRxnClass: 157,
    proteinCount: 0,
    totalProteinsInRxnClass: 353,
    reactionCount: 3,
    totalRxnsInClass: 81,
    hierarchyArray: [
      'Transferases.',
      'Transferring phosphorus-containing groups.',
      'Phosphotransferases with an alcohol group as acceptor.',
    ],
    metCountAverage: '3/157',
    totalReactionAverage: '3/81',
  },
  {
    rxnClass: 'Diphosphotransferases.',
    rxnClassHierarcy:
      'Transferases. | Transferring phosphorus-containing groups. | Diphosphotransferases.',
    ecNumber: '2.7.6.-',
    classLevel: 3,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 6,
    reactionCount: 2,
    totalRxnsInClass: 2,
    hierarchyArray: [
      'Transferases.',
      'Transferring phosphorus-containing groups.',
      'Diphosphotransferases.',
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '2/2',
  },
  {
    rxnClass: 'Phosphoric diester hydrolases.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on ester bonds. | Phosphoric diester hydrolases.',
    ecNumber: '3.1.4.-',
    classLevel: 3,
    metCount: 2,
    totalMetsInRxnClass: 35,
    proteinCount: 0,
    totalProteinsInRxnClass: 174,
    reactionCount: 2,
    totalRxnsInClass: 16,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on ester bonds.',
      'Phosphoric diester hydrolases.',
    ],
    metCountAverage: '2/35',
    totalReactionAverage: '2/16',
  },
  {
    rxnClass: 'Phosphoric monoester hydrolases.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on ester bonds. | Phosphoric monoester hydrolases.',
    ecNumber: '3.1.3.-',
    classLevel: 3,
    metCount: 2,
    totalMetsInRxnClass: 105,
    proteinCount: 0,
    totalProteinsInRxnClass: 595,
    reactionCount: 2,
    totalRxnsInClass: 62,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on ester bonds.',
      'Phosphoric monoester hydrolases.',
    ],
    metCountAverage: '2/105',
    totalReactionAverage: '2/62',
  },
  {
    rxnClass: 'Sulfurtransferases.',
    rxnClassHierarcy:
      'Transferases. | Transferring sulfur-containing groups. | Sulfurtransferases.',
    ecNumber: '2.8.1.-',
    classLevel: 3,
    metCount: 1,
    totalMetsInRxnClass: 43,
    proteinCount: 0,
    totalProteinsInRxnClass: 21,
    reactionCount: 2,
    totalRxnsInClass: 8,
    hierarchyArray: [
      'Transferases.',
      'Transferring sulfur-containing groups.',
      'Sulfurtransferases.',
    ],
    metCountAverage: '1/43',
    totalReactionAverage: '2/8',
  },
  {
    rxnClass: 'Acid--amino-acid ligases (peptide synthases).',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-nitrogen bonds. | Acid--amino-acid ligases (peptide synthases).',
    ecNumber: '6.3.2.-',
    classLevel: 3,
    metCount: 1,
    totalMetsInRxnClass: 31,
    proteinCount: 0,
    totalProteinsInRxnClass: 23,
    reactionCount: 1,
    totalRxnsInClass: 11,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-nitrogen bonds.',
      'Acid--amino-acid ligases (peptide synthases).',
    ],
    metCountAverage: '1/31',
    totalReactionAverage: '1/11',
  },
  {
    rxnClass: 'Acid--ammonia (or amine) ligases (amide synthases).',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-nitrogen bonds. | Acid--ammonia (or amine) ligases (amide synthases).',
    ecNumber: '6.3.1.-',
    classLevel: 3,
    metCount: 1,
    totalMetsInRxnClass: 13,
    proteinCount: 0,
    totalProteinsInRxnClass: 8,
    reactionCount: 1,
    totalRxnsInClass: 3,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-nitrogen bonds.',
      'Acid--ammonia (or amine) ligases (amide synthases).',
    ],
    metCountAverage: '1/13',
    totalReactionAverage: '1/3',
  },
  {
    rxnClass: 'Cyclo-ligases.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-nitrogen bonds. | Cyclo-ligases.',
    ecNumber: '6.3.3.-',
    classLevel: 3,
    metCount: 0,
    totalMetsInRxnClass: 8,
    proteinCount: 1,
    totalProteinsInRxnClass: 8,
    reactionCount: 1,
    totalRxnsInClass: 2,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-nitrogen bonds.',
      'Cyclo-ligases.',
    ],
    proteinCountAverage: '1/8',
    totalReactionAverage: '1/2',
  },
  {
    rxnClass: 'Hydroxymethyl-, formyl- and related transferases.',
    rxnClassHierarcy:
      'Transferases. | Transferring one-carbon groups. | Hydroxymethyl-, formyl- and related transferases.',
    ecNumber: '2.1.2.-',
    classLevel: 3,
    metCount: 0,
    totalMetsInRxnClass: 19,
    proteinCount: 1,
    totalProteinsInRxnClass: 34,
    reactionCount: 1,
    totalRxnsInClass: 6,
    hierarchyArray: [
      'Transferases.',
      'Transferring one-carbon groups.',
      'Hydroxymethyl-, formyl- and related transferases.',
    ],
    proteinCountAverage: '1/34',
    totalReactionAverage: '1/6',
  },
  {
    rxnClass: 'In sulfonyl-containing anhydrides.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on acid anhydrides. | In sulfonyl-containing anhydrides.',
    ecNumber: '3.6.2.-',
    classLevel: 3,
    metCount: 1,
    totalMetsInRxnClass: 5,
    proteinCount: 0,
    totalProteinsInRxnClass: 1,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on acid anhydrides.',
      'In sulfonyl-containing anhydrides.',
    ],
    metCountAverage: '1/5',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass:
      'Molybdenumtransferases or tungstentransferases with sulfide groups as acceptors.',
    rxnClassHierarcy:
      'Transferases. | Transferring molybdenum- or tungsten-containing groups. | Molybdenumtransferases or tungstentransferases with sulfide groups as acceptors.',
    ecNumber: '2.10.1.-',
    classLevel: 3,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 7,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Transferring molybdenum- or tungsten-containing groups.',
      'Molybdenumtransferases or tungstentransferases with sulfide groups as acceptors.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'Nucleotidyltransferases.',
    rxnClassHierarcy:
      'Transferases. | Transferring phosphorus-containing groups. | Nucleotidyltransferases.',
    ecNumber: '2.7.7.-',
    classLevel: 3,
    metCount: 1,
    totalMetsInRxnClass: 77,
    proteinCount: 0,
    totalProteinsInRxnClass: 312,
    reactionCount: 1,
    totalRxnsInClass: 35,
    hierarchyArray: [
      'Transferases.',
      'Transferring phosphorus-containing groups.',
      'Nucleotidyltransferases.',
    ],
    metCountAverage: '1/77',
    totalReactionAverage: '1/35',
  },
  {
    rxnClass: 'Phosphorus-oxygen lyases.',
    rxnClassHierarcy:
      'Lyases. | Phosphorus-oxygen lyases. | Phosphorus-oxygen lyases.',
    ecNumber: '4.6.1.-',
    classLevel: 3,
    metCount: 1,
    totalMetsInRxnClass: 15,
    proteinCount: 0,
    totalProteinsInRxnClass: 78,
    reactionCount: 1,
    totalRxnsInClass: 5,
    hierarchyArray: [
      'Lyases.',
      'Phosphorus-oxygen lyases.',
      'Phosphorus-oxygen lyases.',
    ],
    metCountAverage: '1/15',
    totalReactionAverage: '1/5',
  },
  {
    rxnClass: 'Phosphotransferases with paired acceptors.',
    rxnClassHierarcy:
      'Transferases. | Transferring phosphorus-containing groups. | Phosphotransferases with paired acceptors.',
    ecNumber: '2.7.9.-',
    classLevel: 3,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 6,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Transferring phosphorus-containing groups.',
      'Phosphotransferases with paired acceptors.',
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'Thioether and trialkylsulfonium hydrolases.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on carbon-sulfur bonds. | Thioether and trialkylsulfonium hydrolases.',
    ecNumber: '3.13.2.-',
    classLevel: 3,
    metCount: 1,
    totalMetsInRxnClass: 4,
    proteinCount: 0,
    totalProteinsInRxnClass: 8,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on carbon-sulfur bonds.',
      'Thioether and trialkylsulfonium hydrolases.',
    ],
    metCountAverage: '1/4',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'Transferring groups other than amino-acyl groups.',
    rxnClassHierarcy:
      'Transferases. | Acyltransferases. | Transferring groups other than amino-acyl groups.',
    ecNumber: '2.3.1.-',
    classLevel: 3,
    metCount: 1,
    totalMetsInRxnClass: 208,
    proteinCount: 0,
    totalProteinsInRxnClass: 405,
    reactionCount: 1,
    totalRxnsInClass: 99,
    hierarchyArray: [
      'Transferases.',
      'Acyltransferases.',
      'Transferring groups other than amino-acyl groups.',
    ],
    metCountAverage: '1/208',
    totalReactionAverage: '1/99',
  },
  {
    rxnClass: 'With NAD(+) or NADP(+) as acceptor.',
    rxnClassHierarcy:
      'Oxidoreductases. | Acting on other nitrogenous compounds as donors. | With NAD(+) or NADP(+) as acceptor.',
    ecNumber: '1.7.1.-',
    classLevel: 3,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 11,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Oxidoreductases.',
      'Acting on other nitrogenous compounds as donors.',
      'With NAD(+) or NADP(+) as acceptor.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'nucleoside-diphosphate kinase.',
    rxnClassHierarcy:
      'Transferases. | Transferring phosphorus-containing groups. | Phosphotransferases with a phosphate group as acceptor. | nucleoside-diphosphate kinase.',
    ecNumber: '2.7.4.6',
    classLevel: 4,
    metCount: 0,
    totalMetsInRxnClass: 14,
    proteinCount: 2,
    totalProteinsInRxnClass: 48,
    reactionCount: 6,
    totalRxnsInClass: 6,
    hierarchyArray: [
      'Transferases.',
      'Transferring phosphorus-containing groups.',
      'Phosphotransferases with a phosphate group as acceptor.',
      'nucleoside-diphosphate kinase.',
    ],
    proteinCountAverage: '2/48',
    totalReactionAverage: '6/6',
  },
  {
    rxnClass: 'cholate--CoA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-sulfur bonds. | Acid--thiol ligases. | cholate--CoA ligase.',
    ecNumber: '6.2.1.7',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 14,
    proteinCount: 0,
    totalProteinsInRxnClass: 2,
    reactionCount: 5,
    totalRxnsInClass: 5,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-sulfur bonds.',
      'Acid--thiol ligases.',
      'cholate--CoA ligase.',
    ],
    metCountAverage: '1/14',
    totalReactionAverage: '5/5',
  },
  {
    rxnClass: 'adenylosuccinate lyase.',
    rxnClassHierarcy:
      'Lyases. | Carbon-nitrogen lyases. | Lyases acting on amides, amidines, etc. | adenylosuccinate lyase.',
    ecNumber: '4.3.2.2',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 5,
    proteinCount: 1,
    totalProteinsInRxnClass: 19,
    reactionCount: 3,
    totalRxnsInClass: 2,
    hierarchyArray: [
      'Lyases.',
      'Carbon-nitrogen lyases.',
      'Lyases acting on amides, amidines, etc.',
      'adenylosuccinate lyase.',
    ],
    metCountAverage: '1/5',
    proteinCountAverage: '1/19',
    totalReactionAverage: '3/2',
  },
  {
    rxnClass: 'purine-nucleoside phosphorylase.',
    rxnClassHierarcy:
      'Transferases. | Glycosyltransferases. | Pentosyltransferases. | purine-nucleoside phosphorylase.',
    ecNumber: '2.4.2.1',
    classLevel: 4,
    metCount: 3,
    totalMetsInRxnClass: 13,
    proteinCount: 0,
    totalProteinsInRxnClass: 14,
    reactionCount: 3,
    totalRxnsInClass: 6,
    hierarchyArray: [
      'Transferases.',
      'Glycosyltransferases.',
      'Pentosyltransferases.',
      'purine-nucleoside phosphorylase.',
    ],
    metCountAverage: '3/13',
    totalReactionAverage: '3/6',
  },
  {
    rxnClass: "3'-phosphate/5'-hydroxy nucleic acid ligase.",
    rxnClassHierarcy:
      "Ligases. | Forming phosphoric ester bonds. | Forming phosphoric ester bonds. | 3'-phosphate/5'-hydroxy nucleic acid ligase.",
    ecNumber: '6.5.1.8',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 9,
    proteinCount: 0,
    totalProteinsInRxnClass: 4,
    reactionCount: 2,
    totalRxnsInClass: 2,
    hierarchyArray: [
      'Ligases.',
      'Forming phosphoric ester bonds.',
      'Forming phosphoric ester bonds.',
      "3'-phosphate/5'-hydroxy nucleic acid ligase.",
    ],
    metCountAverage: '1/9',
    totalReactionAverage: '2/2',
  },
  {
    rxnClass: "adenosine-5'-diphospho-5'-[DNA] diphosphatase.",
    rxnClassHierarcy:
      "Hydrolases. | Acting on acid anhydrides. | In phosphorus-containing anhydrides. | adenosine-5'-diphospho-5'-[DNA] diphosphatase.",
    ecNumber: '3.6.1.71',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 5,
    reactionCount: 2,
    totalRxnsInClass: 2,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on acid anhydrides.',
      'In phosphorus-containing anhydrides.',
      "adenosine-5'-diphospho-5'-[DNA] diphosphatase.",
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '2/2',
  },
  {
    rxnClass: 'adenosine-phosphate deaminase.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on carbon-nitrogen bonds, other than peptide bonds. | In cyclic amidines. | adenosine-phosphate deaminase.',
    ecNumber: '3.5.4.17',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 5,
    proteinCount: 1,
    totalProteinsInRxnClass: 10,
    reactionCount: 2,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on carbon-nitrogen bonds, other than peptide bonds.',
      'In cyclic amidines.',
      'adenosine-phosphate deaminase.',
    ],
    metCountAverage: '1/5',
    proteinCountAverage: '1/10',
    totalReactionAverage: '2/1',
  },
  {
    rxnClass: 'adenylate kinase.',
    rxnClassHierarcy:
      'Transferases. | Transferring phosphorus-containing groups. | Phosphotransferases with a phosphate group as acceptor. | adenylate kinase.',
    ecNumber: '2.7.4.3',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 3,
    proteinCount: 1,
    totalProteinsInRxnClass: 14,
    reactionCount: 2,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Transferring phosphorus-containing groups.',
      'Phosphotransferases with a phosphate group as acceptor.',
      'adenylate kinase.',
    ],
    metCountAverage: '1/3',
    proteinCountAverage: '1/14',
    totalReactionAverage: '2/1',
  },
  {
    rxnClass: 'AMP deaminase.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on carbon-nitrogen bonds, other than peptide bonds. | In cyclic amidines. | AMP deaminase.',
    ecNumber: '3.5.4.6',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 5,
    proteinCount: 1,
    totalProteinsInRxnClass: 10,
    reactionCount: 2,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on carbon-nitrogen bonds, other than peptide bonds.',
      'In cyclic amidines.',
      'AMP deaminase.',
    ],
    metCountAverage: '1/5',
    proteinCountAverage: '1/10',
    totalReactionAverage: '2/1',
  },
  {
    rxnClass: 'ATP diphosphatase.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on acid anhydrides. | In phosphorus-containing anhydrides. | ATP diphosphatase.',
    ecNumber: '3.6.1.8',
    classLevel: 4,
    metCount: 2,
    totalMetsInRxnClass: 13,
    proteinCount: 0,
    totalProteinsInRxnClass: 3,
    reactionCount: 2,
    totalRxnsInClass: 5,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on acid anhydrides.',
      'In phosphorus-containing anhydrides.',
      'ATP diphosphatase.',
    ],
    metCountAverage: '2/13',
    totalReactionAverage: '2/5',
  },
  {
    rxnClass: 'diadenosine hexaphosphate hydrolase (AMP-forming).',
    rxnClassHierarcy:
      'Hydrolases. | Acting on acid anhydrides. | In phosphorus-containing anhydrides. | diadenosine hexaphosphate hydrolase (AMP-forming).',
    ecNumber: '3.6.1.60',
    classLevel: 4,
    metCount: 2,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 2,
    reactionCount: 2,
    totalRxnsInClass: 2,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on acid anhydrides.',
      'In phosphorus-containing anhydrides.',
      'diadenosine hexaphosphate hydrolase (AMP-forming).',
    ],
    metCountAverage: '2/7',
    totalReactionAverage: '2/2',
  },
  {
    rxnClass: 'NAD(+) diphosphatase.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on acid anhydrides. | In phosphorus-containing anhydrides. | NAD(+) diphosphatase.',
    ecNumber: '3.6.1.22',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 2,
    reactionCount: 2,
    totalRxnsInClass: 2,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on acid anhydrides.',
      'In phosphorus-containing anhydrides.',
      'NAD(+) diphosphatase.',
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '2/2',
  },
  {
    rxnClass: 'nucleoside diphosphate phosphatase.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on acid anhydrides. | In phosphorus-containing anhydrides. | nucleoside diphosphate phosphatase.',
    ecNumber: '3.6.1.6',
    classLevel: 4,
    metCount: 2,
    totalMetsInRxnClass: 15,
    proteinCount: 0,
    totalProteinsInRxnClass: 20,
    reactionCount: 2,
    totalRxnsInClass: 6,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on acid anhydrides.',
      'In phosphorus-containing anhydrides.',
      'nucleoside diphosphate phosphatase.',
    ],
    metCountAverage: '2/15',
    totalReactionAverage: '2/6',
  },
  {
    rxnClass: 'nucleoside-triphosphate--adenylate kinase.',
    rxnClassHierarcy:
      'Transferases. | Transferring phosphorus-containing groups. | Phosphotransferases with a phosphate group as acceptor. | nucleoside-triphosphate--adenylate kinase.',
    ecNumber: '2.7.4.10',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 4,
    proteinCount: 1,
    totalProteinsInRxnClass: 11,
    reactionCount: 2,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Transferring phosphorus-containing groups.',
      'Phosphotransferases with a phosphate group as acceptor.',
      'nucleoside-triphosphate--adenylate kinase.',
    ],
    metCountAverage: '1/4',
    proteinCountAverage: '1/11',
    totalReactionAverage: '2/1',
  },
  {
    rxnClass: 'nucleotide diphosphatase.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on acid anhydrides. | In phosphorus-containing anhydrides. | nucleotide diphosphatase.',
    ecNumber: '3.6.1.9',
    classLevel: 4,
    metCount: 2,
    totalMetsInRxnClass: 27,
    proteinCount: 0,
    totalProteinsInRxnClass: 20,
    reactionCount: 2,
    totalRxnsInClass: 12,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on acid anhydrides.',
      'In phosphorus-containing anhydrides.',
      'nucleotide diphosphatase.',
    ],
    metCountAverage: '2/27',
    totalReactionAverage: '2/12',
  },
  {
    rxnClass: 'serine--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | serine--tRNA ligase.',
    ecNumber: '6.1.1.11',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 9,
    proteinCount: 0,
    totalProteinsInRxnClass: 9,
    reactionCount: 2,
    totalRxnsInClass: 2,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'serine--tRNA ligase.',
    ],
    metCountAverage: '1/9',
    totalReactionAverage: '2/2',
  },
  {
    rxnClass: '2-hydroxy-dATP diphosphatase.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on acid anhydrides. | In phosphorus-containing anhydrides. | 2-hydroxy-dATP diphosphatase.',
    ecNumber: '3.6.1.56',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 5,
    proteinCount: 0,
    totalProteinsInRxnClass: 1,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on acid anhydrides.',
      'In phosphorus-containing anhydrides.',
      '2-hydroxy-dATP diphosphatase.',
    ],
    metCountAverage: '1/5',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: "3',5'-cyclic-AMP phosphodiesterase.",
    rxnClassHierarcy:
      "Hydrolases. | Acting on ester bonds. | Phosphoric diester hydrolases. | 3',5'-cyclic-AMP phosphodiesterase.",
    ecNumber: '3.1.4.53',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 4,
    proteinCount: 0,
    totalProteinsInRxnClass: 56,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on ester bonds.',
      'Phosphoric diester hydrolases.',
      "3',5'-cyclic-AMP phosphodiesterase.",
    ],
    metCountAverage: '1/4',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: "3',5'-cyclic-GMP phosphodiesterase.",
    rxnClassHierarcy:
      "Hydrolases. | Acting on ester bonds. | Phosphoric diester hydrolases. | 3',5'-cyclic-GMP phosphodiesterase.",
    ecNumber: '3.1.4.35',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 4,
    proteinCount: 0,
    totalProteinsInRxnClass: 27,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on ester bonds.',
      'Phosphoric diester hydrolases.',
      "3',5'-cyclic-GMP phosphodiesterase.",
    ],
    metCountAverage: '1/4',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: "3'(2'),5'-bisphosphate nucleotidase.",
    rxnClassHierarcy:
      "Hydrolases. | Acting on ester bonds. | Phosphoric monoester hydrolases. | 3'(2'),5'-bisphosphate nucleotidase.",
    ecNumber: '3.1.3.7',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 4,
    proteinCount: 0,
    totalProteinsInRxnClass: 2,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on ester bonds.',
      'Phosphoric monoester hydrolases.',
      "3'(2'),5'-bisphosphate nucleotidase.",
    ],
    metCountAverage: '1/4',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'acetate--CoA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-sulfur bonds. | Acid--thiol ligases. | acetate--CoA ligase.',
    ecNumber: '6.2.1.1',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 11,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-sulfur bonds.',
      'Acid--thiol ligases.',
      'acetate--CoA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'acetoacetate--CoA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-sulfur bonds. | Acid--thiol ligases. | acetoacetate--CoA ligase.',
    ecNumber: '6.2.1.16',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 2,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-sulfur bonds.',
      'Acid--thiol ligases.',
      'acetoacetate--CoA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'adenine phosphoribosyltransferase.',
    rxnClassHierarcy:
      'Transferases. | Glycosyltransferases. | Pentosyltransferases. | adenine phosphoribosyltransferase.',
    ecNumber: '2.4.2.7',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 4,
    proteinCount: 0,
    totalProteinsInRxnClass: 5,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Glycosyltransferases.',
      'Pentosyltransferases.',
      'adenine phosphoribosyltransferase.',
    ],
    metCountAverage: '1/4',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'adenosine deaminase.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on carbon-nitrogen bonds, other than peptide bonds. | In cyclic amidines. | adenosine deaminase.',
    ecNumber: '3.5.4.4',
    classLevel: 4,
    metCount: 2,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 30,
    reactionCount: 1,
    totalRxnsInClass: 2,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on carbon-nitrogen bonds, other than peptide bonds.',
      'In cyclic amidines.',
      'adenosine deaminase.',
    ],
    metCountAverage: '2/7',
    totalReactionAverage: '1/2',
  },
  {
    rxnClass: 'adenosine kinase.',
    rxnClassHierarcy:
      'Transferases. | Transferring phosphorus-containing groups. | Phosphotransferases with an alcohol group as acceptor. | adenosine kinase.',
    ecNumber: '2.7.1.20',
    classLevel: 4,
    metCount: 2,
    totalMetsInRxnClass: 5,
    proteinCount: 0,
    totalProteinsInRxnClass: 11,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Transferring phosphorus-containing groups.',
      'Phosphotransferases with an alcohol group as acceptor.',
      'adenosine kinase.',
    ],
    metCountAverage: '2/5',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'adenosylhomocysteinase.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on carbon-sulfur bonds. | Thioether and trialkylsulfonium hydrolases. | adenosylhomocysteinase.',
    ecNumber: '3.13.2.1',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 4,
    proteinCount: 0,
    totalProteinsInRxnClass: 8,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on carbon-sulfur bonds.',
      'Thioether and trialkylsulfonium hydrolases.',
      'adenosylhomocysteinase.',
    ],
    metCountAverage: '1/4',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'adenylosuccinate synthase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-nitrogen bonds. | Other carbon--nitrogen ligases. | adenylosuccinate synthase.',
    ecNumber: '6.3.4.4',
    classLevel: 4,
    metCount: 0,
    totalMetsInRxnClass: 7,
    proteinCount: 1,
    totalProteinsInRxnClass: 5,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-nitrogen bonds.',
      'Other carbon--nitrogen ligases.',
      'adenylosuccinate synthase.',
    ],
    proteinCountAverage: '1/5',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'adenylylsulfatase.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on acid anhydrides. | In sulfonyl-containing anhydrides. | adenylylsulfatase.',
    ecNumber: '3.6.2.1',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 5,
    proteinCount: 0,
    totalProteinsInRxnClass: 1,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on acid anhydrides.',
      'In sulfonyl-containing anhydrides.',
      'adenylylsulfatase.',
    ],
    metCountAverage: '1/5',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'ADP-ribose diphosphatase.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on acid anhydrides. | In phosphorus-containing anhydrides. | ADP-ribose diphosphatase.',
    ecNumber: '3.6.1.13',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 5,
    proteinCount: 0,
    totalProteinsInRxnClass: 4,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on acid anhydrides.',
      'In phosphorus-containing anhydrides.',
      'ADP-ribose diphosphatase.',
    ],
    metCountAverage: '1/5',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'ADP-specific glucose/glucosamine kinase.',
    rxnClassHierarcy:
      'Transferases. | Transferring phosphorus-containing groups. | Phosphotransferases with an alcohol group as acceptor. | ADP-specific glucose/glucosamine kinase.',
    ecNumber: '2.7.1.147',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 5,
    proteinCount: 0,
    totalProteinsInRxnClass: 1,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Transferring phosphorus-containing groups.',
      'Phosphotransferases with an alcohol group as acceptor.',
      'ADP-specific glucose/glucosamine kinase.',
    ],
    metCountAverage: '1/5',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'alanine--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | alanine--tRNA ligase.',
    ecNumber: '6.1.1.7',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 15,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'alanine--tRNA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'arachidonate--CoA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-sulfur bonds. | Acid--thiol ligases. | arachidonate--CoA ligase.',
    ecNumber: '6.2.1.15',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 32,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-sulfur bonds.',
      'Acid--thiol ligases.',
      'arachidonate--CoA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'arginine--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | arginine--tRNA ligase.',
    ecNumber: '6.1.1.19',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 14,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'arginine--tRNA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'argininosuccinate synthase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-nitrogen bonds. | Other carbon--nitrogen ligases. | argininosuccinate synthase.',
    ecNumber: '6.3.4.5',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 1,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-nitrogen bonds.',
      'Other carbon--nitrogen ligases.',
      'argininosuccinate synthase.',
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'asparagine synthase (glutamine-hydrolyzing).',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-nitrogen bonds. | Carbon--nitrogen ligases with glutamine as amido-N-donor. | asparagine synthase (glutamine-hydrolyzing).',
    ecNumber: '6.3.5.4',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 9,
    proteinCount: 0,
    totalProteinsInRxnClass: 3,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-nitrogen bonds.',
      'Carbon--nitrogen ligases with glutamine as amido-N-donor.',
      'asparagine synthase (glutamine-hydrolyzing).',
    ],
    metCountAverage: '1/9',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'asparagine--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | asparagine--tRNA ligase.',
    ecNumber: '6.1.1.22',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 3,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'asparagine--tRNA ligase.',
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'aspartate--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | aspartate--tRNA ligase.',
    ecNumber: '6.1.1.12',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 5,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'aspartate--tRNA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'benzoate--CoA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-sulfur bonds. | Acid--thiol ligases. | benzoate--CoA ligase.',
    ecNumber: '6.2.1.25',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 3,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-sulfur bonds.',
      'Acid--thiol ligases.',
      'benzoate--CoA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'biotin--[biotin carboxyl-carrier protein] ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-nitrogen bonds. | Other carbon--nitrogen ligases. | biotin--[biotin carboxyl-carrier protein] ligase.',
    ecNumber: '6.3.4.15',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 1,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-nitrogen bonds.',
      'Other carbon--nitrogen ligases.',
      'biotin--[biotin carboxyl-carrier protein] ligase.',
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'biotin--[methylcrotonoyl-CoA-carboxylase] ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-nitrogen bonds. | Other carbon--nitrogen ligases. | biotin--[methylcrotonoyl-CoA-carboxylase] ligase.',
    ecNumber: '6.3.4.11',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 1,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-nitrogen bonds.',
      'Other carbon--nitrogen ligases.',
      'biotin--[methylcrotonoyl-CoA-carboxylase] ligase.',
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'biotin--[methylmalonyl-CoA-carboxytransferase] ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-nitrogen bonds. | Other carbon--nitrogen ligases. | biotin--[methylmalonyl-CoA-carboxytransferase] ligase.',
    ecNumber: '6.3.4.9',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 1,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-nitrogen bonds.',
      'Other carbon--nitrogen ligases.',
      'biotin--[methylmalonyl-CoA-carboxytransferase] ligase.',
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'biotin--[propionyl-CoA-carboxylase (ATP-hydrolyzing)] ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-nitrogen bonds. | Other carbon--nitrogen ligases. | biotin--[propionyl-CoA-carboxylase (ATP-hydrolyzing)] ligase.',
    ecNumber: '6.3.4.10',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 1,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-nitrogen bonds.',
      'Other carbon--nitrogen ligases.',
      'biotin--[propionyl-CoA-carboxylase (ATP-hydrolyzing)] ligase.',
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: "bis(5'-adenosyl)-triphosphatase.",
    rxnClassHierarcy:
      "Hydrolases. | Acting on acid anhydrides. | In phosphorus-containing anhydrides. | bis(5'-adenosyl)-triphosphatase.",
    ecNumber: '3.6.1.29',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 5,
    proteinCount: 0,
    totalProteinsInRxnClass: 2,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on acid anhydrides.',
      'In phosphorus-containing anhydrides.',
      "bis(5'-adenosyl)-triphosphatase.",
    ],
    metCountAverage: '1/5',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: "bis(5'-nucleosyl)-tetraphosphatase (asymmetrical).",
    rxnClassHierarcy:
      "Hydrolases. | Acting on acid anhydrides. | In phosphorus-containing anhydrides. | bis(5'-nucleosyl)-tetraphosphatase (asymmetrical).",
    ecNumber: '3.6.1.17',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 5,
    proteinCount: 0,
    totalProteinsInRxnClass: 1,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on acid anhydrides.',
      'In phosphorus-containing anhydrides.',
      "bis(5'-nucleosyl)-tetraphosphatase (asymmetrical).",
    ],
    metCountAverage: '1/5',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'cysteine--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | cysteine--tRNA ligase.',
    ecNumber: '6.1.1.16',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 8,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'cysteine--tRNA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'deoxyadenosine kinase.',
    rxnClassHierarcy:
      'Transferases. | Transferring phosphorus-containing groups. | Phosphotransferases with an alcohol group as acceptor. | deoxyadenosine kinase.',
    ecNumber: '2.7.1.76',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 5,
    proteinCount: 0,
    totalProteinsInRxnClass: 5,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Transferring phosphorus-containing groups.',
      'Phosphotransferases with an alcohol group as acceptor.',
      'deoxyadenosine kinase.',
    ],
    metCountAverage: '1/5',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'deoxynucleoside kinase.',
    rxnClassHierarcy:
      'Transferases. | Transferring phosphorus-containing groups. | Phosphotransferases with an alcohol group as acceptor. | deoxynucleoside kinase.',
    ecNumber: '2.7.1.145',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 11,
    proteinCount: 0,
    totalProteinsInRxnClass: 14,
    reactionCount: 1,
    totalRxnsInClass: 4,
    hierarchyArray: [
      'Transferases.',
      'Transferring phosphorus-containing groups.',
      'Phosphotransferases with an alcohol group as acceptor.',
      'deoxynucleoside kinase.',
    ],
    metCountAverage: '1/11',
    totalReactionAverage: '1/4',
  },
  {
    rxnClass: 'diadenosine hexaphosphate hydrolase (ATP-forming).',
    rxnClassHierarcy:
      'Hydrolases. | Acting on acid anhydrides. | In phosphorus-containing anhydrides. | diadenosine hexaphosphate hydrolase (ATP-forming).',
    ecNumber: '3.6.1.61',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 8,
    proteinCount: 0,
    totalProteinsInRxnClass: 2,
    reactionCount: 1,
    totalRxnsInClass: 3,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on acid anhydrides.',
      'In phosphorus-containing anhydrides.',
      'diadenosine hexaphosphate hydrolase (ATP-forming).',
    ],
    metCountAverage: '1/8',
    totalReactionAverage: '1/3',
  },
  {
    rxnClass: 'diphthine--ammonia ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-nitrogen bonds. | Acid--ammonia (or amine) ligases (amide synthases). | diphthine--ammonia ligase.',
    ecNumber: '6.3.1.14',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 3,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-nitrogen bonds.',
      'Acid--ammonia (or amine) ligases (amide synthases).',
      'diphthine--ammonia ligase.',
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: "DNA-3'-diphospho-5'-guanosine diphosphatase.",
    rxnClassHierarcy:
      "Hydrolases. | Acting on acid anhydrides. | In phosphorus-containing anhydrides. | DNA-3'-diphospho-5'-guanosine diphosphatase.",
    ecNumber: '3.6.1.72',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 5,
    proteinCount: 0,
    totalProteinsInRxnClass: 5,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on acid anhydrides.',
      'In phosphorus-containing anhydrides.',
      "DNA-3'-diphospho-5'-guanosine diphosphatase.",
    ],
    metCountAverage: '1/5',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'FAD-AMP lyase (cyclizing).',
    rxnClassHierarcy:
      'Lyases. | Phosphorus-oxygen lyases. | Phosphorus-oxygen lyases. | FAD-AMP lyase (cyclizing).',
    ecNumber: '4.6.1.15',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 4,
    proteinCount: 0,
    totalProteinsInRxnClass: 3,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Lyases.',
      'Phosphorus-oxygen lyases.',
      'Phosphorus-oxygen lyases.',
      'FAD-AMP lyase (cyclizing).',
    ],
    metCountAverage: '1/4',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'glutamate--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | glutamate--tRNA ligase.',
    ecNumber: '6.1.1.17',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 8,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'glutamate--tRNA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'glutamate--tRNA(Gln) ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | glutamate--tRNA(Gln) ligase.',
    ecNumber: '6.1.1.24',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 1,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'glutamate--tRNA(Gln) ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'glutamine--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | glutamine--tRNA ligase.',
    ecNumber: '6.1.1.18',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 9,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'glutamine--tRNA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'glycine--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | glycine--tRNA ligase.',
    ecNumber: '6.1.1.14',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 9,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'glycine--tRNA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'GMP reductase.',
    rxnClassHierarcy:
      'Oxidoreductases. | Acting on other nitrogenous compounds as donors. | With NAD(+) or NADP(+) as acceptor. | GMP reductase.',
    ecNumber: '1.7.1.7',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 11,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Oxidoreductases.',
      'Acting on other nitrogenous compounds as donors.',
      'With NAD(+) or NADP(+) as acceptor.',
      'GMP reductase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'GMP synthase (glutamine-hydrolyzing).',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-nitrogen bonds. | Carbon--nitrogen ligases with glutamine as amido-N-donor. | GMP synthase (glutamine-hydrolyzing).',
    ecNumber: '6.3.5.2',
    classLevel: 4,
    metCount: 2,
    totalMetsInRxnClass: 9,
    proteinCount: 0,
    totalProteinsInRxnClass: 1,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-nitrogen bonds.',
      'Carbon--nitrogen ligases with glutamine as amido-N-donor.',
      'GMP synthase (glutamine-hydrolyzing).',
    ],
    metCountAverage: '2/9',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'guanosine phosphorylase.',
    rxnClassHierarcy:
      'Transferases. | Glycosyltransferases. | Pentosyltransferases. | guanosine phosphorylase.',
    ecNumber: '2.4.2.15',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 4,
    proteinCount: 0,
    totalProteinsInRxnClass: 8,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Glycosyltransferases.',
      'Pentosyltransferases.',
      'guanosine phosphorylase.',
    ],
    metCountAverage: '1/4',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'guanosine-diphosphatase.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on acid anhydrides. | In phosphorus-containing anhydrides. | guanosine-diphosphatase.',
    ecNumber: '3.6.1.42',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 5,
    proteinCount: 0,
    totalProteinsInRxnClass: 10,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on acid anhydrides.',
      'In phosphorus-containing anhydrides.',
      'guanosine-diphosphatase.',
    ],
    metCountAverage: '1/5',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'guanylate kinase.',
    rxnClassHierarcy:
      'Transferases. | Transferring phosphorus-containing groups. | Phosphotransferases with a phosphate group as acceptor. | guanylate kinase.',
    ecNumber: '2.7.4.8',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 4,
    proteinCount: 0,
    totalProteinsInRxnClass: 1,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Transferring phosphorus-containing groups.',
      'Phosphotransferases with a phosphate group as acceptor.',
      'guanylate kinase.',
    ],
    metCountAverage: '1/4',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'histidine--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | histidine--tRNA ligase.',
    ecNumber: '6.1.1.21',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 20,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'histidine--tRNA ligase.',
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'hypoxanthine phosphoribosyltransferase.',
    rxnClassHierarcy:
      'Transferases. | Glycosyltransferases. | Pentosyltransferases. | hypoxanthine phosphoribosyltransferase.',
    ecNumber: '2.4.2.8',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 3,
    reactionCount: 1,
    totalRxnsInClass: 2,
    hierarchyArray: [
      'Transferases.',
      'Glycosyltransferases.',
      'Pentosyltransferases.',
      'hypoxanthine phosphoribosyltransferase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/2',
  },
  {
    rxnClass: "IMP-specific 5'-nucleotidase.",
    rxnClassHierarcy:
      "Hydrolases. | Acting on ester bonds. | Phosphoric monoester hydrolases. | IMP-specific 5'-nucleotidase.",
    ecNumber: '3.1.3.99',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 4,
    proteinCount: 0,
    totalProteinsInRxnClass: 7,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on ester bonds.',
      'Phosphoric monoester hydrolases.',
      "IMP-specific 5'-nucleotidase.",
    ],
    metCountAverage: '1/4',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'inosine diphosphate phosphatase.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on acid anhydrides. | In phosphorus-containing anhydrides. | inosine diphosphate phosphatase.',
    ecNumber: '3.6.1.64',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 11,
    reactionCount: 1,
    totalRxnsInClass: 2,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on acid anhydrides.',
      'In phosphorus-containing anhydrides.',
      'inosine diphosphate phosphatase.',
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '1/2',
  },
  {
    rxnClass: 'isoleucine--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | isoleucine--tRNA ligase.',
    ecNumber: '6.1.1.5',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 17,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'isoleucine--tRNA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'leucine--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | leucine--tRNA ligase.',
    ecNumber: '6.1.1.4',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 19,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'leucine--tRNA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'long-chain-fatty-acid--CoA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-sulfur bonds. | Acid--thiol ligases. | long-chain-fatty-acid--CoA ligase.',
    ecNumber: '6.2.1.3',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 49,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-sulfur bonds.',
      'Acid--thiol ligases.',
      'long-chain-fatty-acid--CoA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'lysine--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | lysine--tRNA ligase.',
    ecNumber: '6.1.1.6',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 1,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'lysine--tRNA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'malonate--CoA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-sulfur bonds. | Acid--thiol ligases. | malonate--CoA ligase.',
    ecNumber: '6.2.1.76',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 1,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-sulfur bonds.',
      'Acid--thiol ligases.',
      'malonate--CoA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'medium-chain acyl-CoA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-sulfur bonds. | Acid--thiol ligases. | medium-chain acyl-CoA ligase.',
    ecNumber: '6.2.1.2',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 34,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-sulfur bonds.',
      'Acid--thiol ligases.',
      'medium-chain acyl-CoA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'methionine--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | methionine--tRNA ligase.',
    ecNumber: '6.1.1.10',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 6,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'methionine--tRNA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'Mn(2+)-dependent ADP-ribose/CDP-alcohol diphosphatase.',
    rxnClassHierarcy:
      'Hydrolases. | Acting on acid anhydrides. | In phosphorus-containing anhydrides. | Mn(2+)-dependent ADP-ribose/CDP-alcohol diphosphatase.',
    ecNumber: '3.6.1.53',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 8,
    proteinCount: 0,
    totalProteinsInRxnClass: 4,
    reactionCount: 1,
    totalRxnsInClass: 2,
    hierarchyArray: [
      'Hydrolases.',
      'Acting on acid anhydrides.',
      'In phosphorus-containing anhydrides.',
      'Mn(2+)-dependent ADP-ribose/CDP-alcohol diphosphatase.',
    ],
    metCountAverage: '1/8',
    totalReactionAverage: '1/2',
  },
  {
    rxnClass: 'molybdopterin molybdotransferase.',
    rxnClassHierarcy:
      'Transferases. | Transferring molybdenum- or tungsten-containing groups. | Molybdenumtransferases or tungstentransferases with sulfide groups as acceptors. | molybdopterin molybdotransferase.',
    ecNumber: '2.10.1.1',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 7,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Transferring molybdenum- or tungsten-containing groups.',
      'Molybdenumtransferases or tungstentransferases with sulfide groups as acceptors.',
      'molybdopterin molybdotransferase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'molybdopterin synthase sulfurtransferase.',
    rxnClassHierarcy:
      'Transferases. | Transferring sulfur-containing groups. | Sulfurtransferases. | molybdopterin synthase sulfurtransferase.',
    ecNumber: '2.8.1.11',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 8,
    proteinCount: 0,
    totalProteinsInRxnClass: 1,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Transferring sulfur-containing groups.',
      'Sulfurtransferases.',
      'molybdopterin synthase sulfurtransferase.',
    ],
    metCountAverage: '1/8',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'N(6)-L-threonylcarbamoyladenine synthase.',
    rxnClassHierarcy:
      'Transferases. | Acyltransferases. | Transferring groups other than amino-acyl groups. | N(6)-L-threonylcarbamoyladenine synthase.',
    ecNumber: '2.3.1.234',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 5,
    proteinCount: 0,
    totalProteinsInRxnClass: 8,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Acyltransferases.',
      'Transferring groups other than amino-acyl groups.',
      'N(6)-L-threonylcarbamoyladenine synthase.',
    ],
    metCountAverage: '1/5',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'NAD(+) synthase (glutamine-hydrolyzing).',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-nitrogen bonds. | Carbon--nitrogen ligases with glutamine as amido-N-donor. | NAD(+) synthase (glutamine-hydrolyzing).',
    ecNumber: '6.3.5.1',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 9,
    proteinCount: 0,
    totalProteinsInRxnClass: 1,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-nitrogen bonds.',
      'Carbon--nitrogen ligases with glutamine as amido-N-donor.',
      'NAD(+) synthase (glutamine-hydrolyzing).',
    ],
    metCountAverage: '1/9',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'phenylalanine--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | phenylalanine--tRNA ligase.',
    ecNumber: '6.1.1.20',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 4,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'phenylalanine--tRNA ligase.',
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'phosphopantothenate--cysteine ligase (ATP).',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-nitrogen bonds. | Acid--amino-acid ligases (peptide synthases). | phosphopantothenate--cysteine ligase (ATP).',
    ecNumber: '6.3.2.51',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 1,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-nitrogen bonds.',
      'Acid--amino-acid ligases (peptide synthases).',
      'phosphopantothenate--cysteine ligase (ATP).',
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'phosphoribosylamine--glycine ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-nitrogen bonds. | Other carbon--nitrogen ligases. | phosphoribosylamine--glycine ligase.',
    ecNumber: '6.3.4.13',
    classLevel: 4,
    metCount: 0,
    totalMetsInRxnClass: 7,
    proteinCount: 1,
    totalProteinsInRxnClass: 3,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-nitrogen bonds.',
      'Other carbon--nitrogen ligases.',
      'phosphoribosylamine--glycine ligase.',
    ],
    proteinCountAverage: '1/3',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'phosphoribosylformylglycinamidine cyclo-ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-nitrogen bonds. | Cyclo-ligases. | phosphoribosylformylglycinamidine cyclo-ligase.',
    ecNumber: '6.3.3.1',
    classLevel: 4,
    metCount: 0,
    totalMetsInRxnClass: 6,
    proteinCount: 1,
    totalProteinsInRxnClass: 3,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-nitrogen bonds.',
      'Cyclo-ligases.',
      'phosphoribosylformylglycinamidine cyclo-ligase.',
    ],
    proteinCountAverage: '1/3',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'phosphoribosylglycinamide formyltransferase 1.',
    rxnClassHierarcy:
      'Transferases. | Transferring one-carbon groups. | Hydroxymethyl-, formyl- and related transferases. | phosphoribosylglycinamide formyltransferase 1.',
    ecNumber: '2.1.2.2',
    classLevel: 4,
    metCount: 0,
    totalMetsInRxnClass: 5,
    proteinCount: 1,
    totalProteinsInRxnClass: 3,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Transferring one-carbon groups.',
      'Hydroxymethyl-, formyl- and related transferases.',
      'phosphoribosylglycinamide formyltransferase 1.',
    ],
    proteinCountAverage: '1/3',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'phytanate--CoA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-sulfur bonds. | Acid--thiol ligases. | phytanate--CoA ligase.',
    ecNumber: '6.2.1.24',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 2,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-sulfur bonds.',
      'Acid--thiol ligases.',
      'phytanate--CoA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'proline--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | proline--tRNA ligase.',
    ecNumber: '6.1.1.15',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 3,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'proline--tRNA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'propionate--CoA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-sulfur bonds. | Acid--thiol ligases. | propionate--CoA ligase.',
    ecNumber: '6.2.1.17',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 9,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-sulfur bonds.',
      'Acid--thiol ligases.',
      'propionate--CoA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'ribose-phosphate diphosphokinase.',
    rxnClassHierarcy:
      'Transferases. | Transferring phosphorus-containing groups. | Diphosphotransferases. | ribose-phosphate diphosphokinase.',
    ecNumber: '2.7.6.1',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 5,
    proteinCount: 0,
    totalProteinsInRxnClass: 4,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Transferring phosphorus-containing groups.',
      'Diphosphotransferases.',
      'ribose-phosphate diphosphokinase.',
    ],
    metCountAverage: '1/5',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: "RNA 3'-terminal-phosphate cyclase (ATP).",
    rxnClassHierarcy:
      "Ligases. | Forming phosphoric ester bonds. | Forming phosphoric ester bonds. | RNA 3'-terminal-phosphate cyclase (ATP).",
    ecNumber: '6.5.1.4',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 5,
    proteinCount: 0,
    totalProteinsInRxnClass: 2,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming phosphoric ester bonds.',
      'Forming phosphoric ester bonds.',
      "RNA 3'-terminal-phosphate cyclase (ATP).",
    ],
    metCountAverage: '1/5',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'selenide, water dikinase.',
    rxnClassHierarcy:
      'Transferases. | Transferring phosphorus-containing groups. | Phosphotransferases with paired acceptors. | selenide, water dikinase.',
    ecNumber: '2.7.9.3',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 6,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Transferring phosphorus-containing groups.',
      'Phosphotransferases with paired acceptors.',
      'selenide, water dikinase.',
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'thiamine diphosphokinase.',
    rxnClassHierarcy:
      'Transferases. | Transferring phosphorus-containing groups. | Diphosphotransferases. | thiamine diphosphokinase.',
    ecNumber: '2.7.6.2',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 5,
    proteinCount: 0,
    totalProteinsInRxnClass: 2,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Transferring phosphorus-containing groups.',
      'Diphosphotransferases.',
      'thiamine diphosphokinase.',
    ],
    metCountAverage: '1/5',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'threonine--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | threonine--tRNA ligase.',
    ecNumber: '6.1.1.3',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 11,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'threonine--tRNA ligase.',
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'tRNA-5-taurinomethyluridine 2-sulfurtransferase.',
    rxnClassHierarcy:
      'Transferases. | Transferring sulfur-containing groups. | Sulfurtransferases. | tRNA-5-taurinomethyluridine 2-sulfurtransferase.',
    ecNumber: '2.8.1.14',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 10,
    proteinCount: 0,
    totalProteinsInRxnClass: 5,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Transferring sulfur-containing groups.',
      'Sulfurtransferases.',
      'tRNA-5-taurinomethyluridine 2-sulfurtransferase.',
    ],
    metCountAverage: '1/10',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'tRNA(His) guanylyltransferase.',
    rxnClassHierarcy:
      'Transferases. | Transferring phosphorus-containing groups. | Nucleotidyltransferases. | tRNA(His) guanylyltransferase.',
    ecNumber: '2.7.7.79',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 8,
    proteinCount: 0,
    totalProteinsInRxnClass: 3,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Transferases.',
      'Transferring phosphorus-containing groups.',
      'Nucleotidyltransferases.',
      'tRNA(His) guanylyltransferase.',
    ],
    metCountAverage: '1/8',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'tryptophan--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | tryptophan--tRNA ligase.',
    ecNumber: '6.1.1.2',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 7,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'tryptophan--tRNA ligase.',
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'tyrosine--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | tyrosine--tRNA ligase.',
    ecNumber: '6.1.1.1',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 7,
    proteinCount: 0,
    totalProteinsInRxnClass: 9,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'tyrosine--tRNA ligase.',
    ],
    metCountAverage: '1/7',
    totalReactionAverage: '1/1',
  },
  {
    rxnClass: 'valine--tRNA ligase.',
    rxnClassHierarcy:
      'Ligases. | Forming carbon-oxygen bonds. | Ligases forming aminoacyl-tRNA and related compounds. | valine--tRNA ligase.',
    ecNumber: '6.1.1.9',
    classLevel: 4,
    metCount: 1,
    totalMetsInRxnClass: 6,
    proteinCount: 0,
    totalProteinsInRxnClass: 16,
    reactionCount: 1,
    totalRxnsInClass: 1,
    hierarchyArray: [
      'Ligases.',
      'Forming carbon-oxygen bonds.',
      'Ligases forming aminoacyl-tRNA and related compounds.',
      'valine--tRNA ligase.',
    ],
    metCountAverage: '1/6',
    totalReactionAverage: '1/1',
  },
];
