scalar JSON
extend schema @mutation(operations: [])

type Disease @node {
  classificationLevel: [String!]
  disorderType: [String!]
  gardId: String!
  gardName: String!
  icd10cm: [String!]
  mesh: [String!]
  omim: String
  orphanet: String
  synonyms: [String!]
  umls: String
  doid: [String!]
  ncit: [String!]
  sctid: [String!]
  mondo: String
  medGen: String
  omimps: String
  diseaseType: String
  geneCount: Int!
  phenotypeCount: Int!
  diseaseSubClassOf: [Disease!]!
    @relationship(type: "subclass_of", direction: IN)
  subClassOfDisease: [Disease!]!
    @relationship(type: "subclass_of", direction: OUT)
  hasAssociatedGene: [Gene!]!
    @relationship(
      type: "has_associated_gene"
      direction: OUT
      properties: "AssociatedWithGeneProperties"
    )

  hasPhenotype: [Phenotype!]!
    @relationship(
      type: "has_phenotype"
      direction: OUT
      properties: "HasPhenotypeProperties"
    )
  hasClinicalTrial: [ClinicalTrial!]!
    @relationship(type: "has_clinical_trial", direction: OUT)
  hasMappedCondition: [Condition!]!
    @relationship(type: "has_mapped_condition", direction: OUT)
  hasMentionIn: [Article!]!
    @relationship(type: "has_mention_in", direction: OUT)
}

type Condition @node {
  condition: String
}
