import '@angular/compiler';
import '@analogjs/vitest-angular/setup-zone';

import {
  BrowserTestingModule,
  platformBrowserTesting,
} from '@angular/platform-browser/testing';
import { getTestBed } from '@angular/core/testing';

getTestBed().initTestEnvironment(
    BrowserTestingModule,
    platformBrowserTesting(),
);

export const DISEASEENTITIESMOCK = {
  entities: {
    'GARD:0008557': {
      articleCount: 0,
      classificationLevel: 'Subtype of disorder',
      dataSource: 'Orphanet+OMIM',
      dataSourceId: 'OMIM:300062',
      diseaseOntology: ['112027'],
      disorderType: ['Etiological subtype'],
      name: 'Intellectual developmental disorder, x-linked 14',
      gardId: 'GARD:0008557',
      geneticAlliance: ['4664'],
      geneticsHomeReference: null,
      icd10: null,
      icd10cm: null,
      icd11: null,
      mesh: null,
      medra: null,
      omim: ['300062'],
      orphanet: null,
      snomed: null,
      synonyms: [],
      umls: ['C0796220'],
      epiArticles: [],
      nonEpiArticles: [],
      epiCount: 0,
      nonEpiCount: 0,
      projects: [],
      projectCount: 0,
      clinicalTrials: [],
      clinicalTrialCount: 0,
      geneAssociations: [
        {
          associationStatus: 'Unknown',
          associationType: 'The disease phenotype itself was mapped',
          reference: [
            {
              code: 'OMIM:300062',
              url: 'https://www.omim.org/entry/300062',
            },
          ],
          gene: {
            ensembl: null,
            geneSymbol: 'MRX14',
            geneIdentifier: 'GeneID:4378',
            geneSynonyms: ['XLID14'],
            geneTitle: 'Intellectual developmental disorder, X-linked 14',
            locus: 'Xp11.3-q13.3',
            omim: '300062',
            swissprot: null,
            reactome: null,
            __typename: 'Gene',
            iuphar: null,
          },
          __typename: 'AssociatedWithGeneProperties',
        },
      ],
      phenotypeAssociations: [
        {
          evidence: {
            code: 'IEA',
            value: 'Inferred from Electronic Annotation',
          },
          hpoFrequency: null,
          reference: [
            {
              code: 'OMIM:300062',
              url: 'https://www.omim.org/entry/300062',
            },
          ],
          phenotype: {
            hpoId: 'HP:0001999',
            hpoTerm: 'Abnormal facial shape',
            modifier: null,
            online: true,
            onset: null,
            sex: null,
            __typename: 'Phenotype',
          },
          frequencyRank: 0,
          __typename: 'HasPhenotypeProperties',
          status: false,
        },
        {
          evidence: {
            code: 'IEA',
            value: 'Inferred from Electronic Annotation',
          },
          hpoFrequency: null,
          reference: [
            {
              code: 'OMIM:300062',
              url: 'https://www.omim.org/entry/300062',
            },
          ],
          phenotype: {
            hpoId: 'HP:0000053',
            hpoTerm: 'Macroorchidism',
            modifier: null,
            online: true,
            onset: null,
            sex: null,
            __typename: 'Phenotype',
          },
          frequencyRank: 0,
          __typename: 'HasPhenotypeProperties',
          status: false,
        },
        {
          evidence: {
            code: 'IEA',
            value: 'Inferred from Electronic Annotation',
          },
          hpoFrequency: null,
          reference: [
            {
              code: 'OMIM:300062',
              url: 'https://www.omim.org/entry/300062',
            },
          ],
          phenotype: {
            hpoId: 'HP:0001250',
            hpoTerm: 'Seizure',
            modifier: null,
            online: true,
            onset: null,
            sex: null,
            __typename: 'Phenotype',
          },
          frequencyRank: 0,
          __typename: 'HasPhenotypeProperties',
          status: false,
        },
        {
          evidence: {
            code: 'IEA',
            value: 'Inferred from Electronic Annotation',
          },
          hpoFrequency: null,
          reference: [
            {
              code: 'OMIM:300062',
              url: 'https://www.omim.org/entry/300062',
            },
          ],
          phenotype: {
            hpoId: 'HP:0002342',
            hpoTerm: 'Intellectual disability, moderate',
            modifier: null,
            online: true,
            onset: null,
            sex: null,
            __typename: 'Phenotype',
          },
          frequencyRank: 0,
          __typename: 'HasPhenotypeProperties',
          status: false,
        },
        {
          evidence: {
            code: 'IEA',
            value: 'Inferred from Electronic Annotation',
          },
          hpoFrequency: null,
          reference: [
            {
              code: 'OMIM:300062',
              url: 'https://www.omim.org/entry/300062',
            },
          ],
          phenotype: {
            hpoId: 'HP:0002465',
            hpoTerm: 'Poor speech',
            modifier: null,
            online: true,
            onset: null,
            sex: null,
            __typename: 'Phenotype',
          },
          frequencyRank: 0,
          __typename: 'HasPhenotypeProperties',
          status: false,
        },
      ],
      geneCount: 1,
      phenotypeCount: 5,
      __typename: 'GARD',
      associatedWithGeneGenesAggregate: {
        __typename: 'GARDGeneAssociatedWithGeneGenesAggregationSelection',
        count: 1,
      },
    },
  },
};

export const DISEASELISTMOCK = {
  diseases: [
    {
      articleCount: 0,
      classificationLevel: 'Subtype of disorder',
      dataSource: 'Orphanet+OMIM',
      dataSourceId: 'OMIM:300062',
      diseaseOntology: ['112027'],
      disorderType: ['Etiological subtype'],
      name: 'Intellectual developmental disorder, x-linked 14',
      gardId: 'GARD:0008557',
      geneticAlliance: ['4664'],
      geneticsHomeReference: null,
      icd10: null,
      icd10cm: null,
      icd11: null,
      mesh: null,
      medra: null,
      omim: ['300062'],
      orphanet: null,
      snomed: null,
      synonyms: [],
      umls: ['C0796220'],
      epiArticles: [],
      nonEpiArticles: [],
      epiCount: 0,
      nonEpiCount: 0,
      projects: [],
      projectCount: 0,
      clinicalTrials: [],
      clinicalTrialCount: 0,
      geneAssociations: [
        {
          associationStatus: 'Unknown',
          associationType: 'The disease phenotype itself was mapped',
          reference: [
            {
              code: 'OMIM:300062',
              url: 'https://www.omim.org/entry/300062',
            },
          ],
          gene: {
            ensembl: null,
            geneSymbol: 'MRX14',
            geneIdentifier: 'GeneID:4378',
            geneSynonyms: ['XLID14'],
            geneTitle: 'Intellectual developmental disorder, X-linked 14',
            locus: 'Xp11.3-q13.3',
            omim: '300062',
            swissprot: null,
            reactome: null,
            __typename: 'Gene',
            iuphar: null,
          },
          __typename: 'AssociatedWithGeneProperties',
        },
      ],
      phenotypeAssociations: [
        {
          evidence: {
            code: 'IEA',
            value: 'Inferred from Electronic Annotation',
          },
          hpoFrequency: null,
          reference: [
            {
              code: 'OMIM:300062',
              url: 'https://www.omim.org/entry/300062',
            },
          ],
          phenotype: {
            hpoId: 'HP:0001999',
            hpoTerm: 'Abnormal facial shape',
            modifier: null,
            online: true,
            onset: null,
            sex: null,
            __typename: 'Phenotype',
          },
          frequencyRank: 0,
          __typename: 'HasPhenotypeProperties',
          status: false,
        },
        {
          evidence: {
            code: 'IEA',
            value: 'Inferred from Electronic Annotation',
          },
          hpoFrequency: null,
          reference: [
            {
              code: 'OMIM:300062',
              url: 'https://www.omim.org/entry/300062',
            },
          ],
          phenotype: {
            hpoId: 'HP:0000053',
            hpoTerm: 'Macroorchidism',
            modifier: null,
            online: true,
            onset: null,
            sex: null,
            __typename: 'Phenotype',
          },
          frequencyRank: 0,
          __typename: 'HasPhenotypeProperties',
          status: false,
        },
        {
          evidence: {
            code: 'IEA',
            value: 'Inferred from Electronic Annotation',
          },
          hpoFrequency: null,
          reference: [
            {
              code: 'OMIM:300062',
              url: 'https://www.omim.org/entry/300062',
            },
          ],
          phenotype: {
            hpoId: 'HP:0001250',
            hpoTerm: 'Seizure',
            modifier: null,
            online: true,
            onset: null,
            sex: null,
            __typename: 'Phenotype',
          },
          frequencyRank: 0,
          __typename: 'HasPhenotypeProperties',
          status: false,
        },
        {
          evidence: {
            code: 'IEA',
            value: 'Inferred from Electronic Annotation',
          },
          hpoFrequency: null,
          reference: [
            {
              code: 'OMIM:300062',
              url: 'https://www.omim.org/entry/300062',
            },
          ],
          phenotype: {
            hpoId: 'HP:0002342',
            hpoTerm: 'Intellectual disability, moderate',
            modifier: null,
            online: true,
            onset: null,
            sex: null,
            __typename: 'Phenotype',
          },
          frequencyRank: 0,
          __typename: 'HasPhenotypeProperties',
          status: false,
        },
        {
          evidence: {
            code: 'IEA',
            value: 'Inferred from Electronic Annotation',
          },
          hpoFrequency: null,
          reference: [
            {
              code: 'OMIM:300062',
              url: 'https://www.omim.org/entry/300062',
            },
          ],
          phenotype: {
            hpoId: 'HP:0002465',
            hpoTerm: 'Poor speech',
            modifier: null,
            online: true,
            onset: null,
            sex: null,
            __typename: 'Phenotype',
          },
          frequencyRank: 0,
          __typename: 'HasPhenotypeProperties',
          status: false,
        },
      ],
      geneCount: 1,
      phenotypeCount: 5,
      associatedWithGeneGenesAggregate: {
        count: 1,
      },
    },
  ],
};
export const SUBSCRIPTIONLISTMOCK = {
  subscriptions: [
    {
      gardID: 'GARD:0002491',
      alerts: ['articles', 'grants', 'trials'],
      diseaseName: 'Glioblastoma',
    },
    {
      alerts: ['articles', 'grants', 'trials'],
      gardID: 'GARD:0020774',
      diseaseName: '16p13.11 microdeletion syndrome',
    },
    {
      gardID: 'GARD:0022513',
      diseaseName: 'Rare developmental defect during embryogenesis',
      alerts: ['articles', 'grants', 'trials'],
    },
    {
      gardID: 'GARD:0010525',
      diseaseName: '15q11.2 microdeletion syndrome',
      alerts: ['articles', 'grants', 'trials'],
    },
    {
      gardID: 'GARD:0017423',
      diseaseName: '15q overgrowth syndrome',
      alerts: ['articles', 'grants', 'trials'],
    },
    {
      gardID: 'GARD:0005679',
      alerts: ['articles', 'grants', 'trials'],
      diseaseName: '49, XXXXY syndrome',
    },
    {
      diseaseName: 'Precocious puberty',
      alerts: ['articles', 'grants', 'trials'],
      gardID: 'GARD:0007446',
    },
    {
      gardID: 'GARD:0005659',
      diseaseName: '17-beta hydroxysteroid dehydrogenase 3 deficiency',
      alerts: ['articles', 'grants', 'trials'],
    },
    {
      gardID: 'GARD:0001469',
      diseaseName: '17-alpha-hydroxylase deficiency',
      alerts: ['articles', 'grants', 'trials'],
    },
    {
      alerts: ['articles', 'trials', 'grants'],
      diseaseName: '48,XXYY syndrome',
      gardID: 'GARD:0005677',
    },
    {
      gardID: 'GARD:0011985',
      alerts: ['trials', 'grants', 'articles'],
      diseaseName: '48,XYYY',
    },
    {
      diseaseName: '14q24.1q24.3 microdeletion syndrome',
      alerts: ['articles', 'grants', 'trials'],
      gardID: 'GARD:0021706',
    },
    {
      gardID: 'GARD:0010935',
      alerts: ['trials'],
      diseaseName: '16q24.3 microdeletion syndrome',
    },
    {
      diseaseName: '14q32 duplication syndrome',
      alerts: ['trials'],
      gardID: 'GARD:0017890',
    },
  ],
};

export const DISEASESTATEMOCK = {
  diseases: {
    ids: [
      'GARD:0017280',
      'GARD:0021052',
      'GARD:0021232',
      'GARD:0021858',
      'GARD:0017414',
      'GARD:0013390',
      'GARD:0021141',
      'GARD:0021737',
      'GARD:0017241',
      'GARD:0020773',
    ],
    entities: {
      'GARD:0017280': {
        articleCount: '1',
        classificationLevel: 'Disorder',
        disorderType: ['Malformation syndrome'],
        name: '10q22.3q23.3 microdeletion syndrome',
        gardId: 'GARD:0017280',
        synonyms: [
          'Del(10)(q22.3q23.3)',
          'Deletion 10q22.3q23.3',
          'Monosomy 10q22.3q23.3',
        ],
        epiCount: 0,
        nonEpiCount: 0,
        projectCount: '0',
        clinicalTrialCount: '0',
        geneCount: '0',
        phenotypeCount: '30',
        __typename: 'GARD',
      },
      'GARD:0021052': {
        articleCount: '0',
        classificationLevel: 'Disorder',
        disorderType: ['Malformation syndrome'],
        name: '10q22.3q23.3 microduplication syndrome',
        gardId: 'GARD:0021052',
        synonyms: ['Dup(10)(q22.3q23.3)', 'Trisomy 10q22.3q23.3'],
        epiCount: 0,
        nonEpiCount: 0,
        projectCount: '0',
        clinicalTrialCount: '0',
        geneCount: '0',
        phenotypeCount: '22',
        __typename: 'GARD',
      },
      'GARD:0021232': {
        articleCount: '0',
        classificationLevel: 'Disorder',
        disorderType: ['Malformation syndrome'],
        name: '11p15.4 microduplication syndrome',
        gardId: 'GARD:0021232',
        synonyms: ['Dup(11)p(15.4)', 'Trisomy 11p15.4'],
        epiCount: 0,
        nonEpiCount: 0,
        projectCount: '0',
        clinicalTrialCount: '0',
        geneCount: '0',
        phenotypeCount: '18',
        __typename: 'GARD',
      },
      'GARD:0021858': {
        articleCount: '1',
        classificationLevel: 'Disorder',
        disorderType: ['Malformation syndrome'],
        name: '11q22.2q22.3 microdeletion syndrome',
        gardId: 'GARD:0021858',
        synonyms: ['Del(11)(q22.2q22.3)', 'Monosomy 11q22.2q22.3'],
        epiCount: 0,
        nonEpiCount: 0,
        projectCount: '0',
        clinicalTrialCount: '0',
        geneCount: '0',
        phenotypeCount: '44',
        __typename: 'GARD',
      },
      'GARD:0017414': {
        articleCount: '2',
        classificationLevel: 'Subtype of disorder',
        disorderType: ['Clinical subtype'],
        name: '12p12.1 microdeletion syndrome',
        gardId: 'GARD:0017414',
        synonyms: ['Del(12)(p12.1)', 'Monosomy 12p12.1'],
        epiCount: 0,
        nonEpiCount: 0,
        projectCount: '0',
        clinicalTrialCount: '0',
        geneCount: '1',
        phenotypeCount: '0',
        __typename: 'GARD',
      },
      'GARD:0013390': {
        articleCount: '21',
        classificationLevel: 'Disorder',
        disorderType: ['Malformation syndrome'],
        name: '12q14 microdeletion syndrome',
        gardId: 'GARD:0013390',
        synonyms: [
          'Del(12)(q14)',
          'Deletion 12q14',
          'Monosomy 12q14',
          'Osteopoikilosis-short stature-intellectual disability syndrome',
        ],
        epiCount: 0,
        nonEpiCount: 0,
        projectCount: '0',
        clinicalTrialCount: '0',
        geneCount: '2',
        phenotypeCount: '37',
        __typename: 'GARD',
      },
      'GARD:0021141': {
        articleCount: '0',
        classificationLevel: 'Disorder',
        disorderType: ['Malformation syndrome'],
        name: '12q15q21.1 microdeletion syndrome',
        gardId: 'GARD:0021141',
        synonyms: [
          'Del(12)(q15)(q21.1)',
          'Deletion 12q15q21.1',
          'Monosomy 12q15q21.1',
        ],
        epiCount: 0,
        nonEpiCount: 0,
        projectCount: '0',
        clinicalTrialCount: '0',
        geneCount: '1',
        phenotypeCount: '0',
        __typename: 'GARD',
      },
      'GARD:0021737': {
        articleCount: '3',
        classificationLevel: 'Disorder',
        disorderType: ['Malformation syndrome'],
        name: '13q12.3 microdeletion syndrome',
        gardId: 'GARD:0021737',
        synonyms: ['Del(13)(q12.3)', 'Monosomy 13q12.3'],
        epiCount: 0,
        nonEpiCount: 0,
        projectCount: '0',
        clinicalTrialCount: '0',
        geneCount: '0',
        phenotypeCount: '30',
        __typename: 'GARD',
      },
      'GARD:0017241': {
        articleCount: '4',
        classificationLevel: 'Disorder',
        disorderType: ['Malformation syndrome'],
        name: '14q11.2 microdeletion syndrome',
        gardId: 'GARD:0017241',
        synonyms: ['Del(14)(q11.2)', 'Monosomy 14q11.2'],
        epiCount: 0,
        nonEpiCount: 0,
        projectCount: '0',
        clinicalTrialCount: '0',
        geneCount: '0',
        phenotypeCount: '25',
        __typename: 'GARD',
      },
      'GARD:0020773': {
        articleCount: '2',
        classificationLevel: 'Disorder',
        disorderType: ['Malformation syndrome'],
        name: '14q11.2 microduplication syndrome',
        gardId: 'GARD:0020773',
        synonyms: ['Dup(14)(q11.2)', 'Trisomy 14q11.2'],
        epiCount: 0,
        nonEpiCount: 0,
        projectCount: '0',
        clinicalTrialCount: '0',
        geneCount: '1',
        phenotypeCount: '0',
        __typename: 'GARD',
      },
    },
    loaded: true,
    error: 'No Error Available',
    typeahead: [],
    diseaseFilters: [
      {
        label: 'Articles by Year',
        parent: 'articles',
        filterable: false,
        page: 1,
        values: [
          {
            term: '2023',
            label: 'Epidemiology Articles',
            count: 9,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2022',
            label: 'Epidemiology Articles',
            count: 44,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2021',
            label: 'Epidemiology Articles',
            count: 41,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2020',
            label: 'Epidemiology Articles',
            count: 18,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2019',
            label: 'Epidemiology Articles',
            count: 10,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2018',
            label: 'Epidemiology Articles',
            count: 6,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2017',
            label: 'Epidemiology Articles',
            count: 5,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2016',
            label: 'Epidemiology Articles',
            count: 3,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2015',
            label: 'Epidemiology Articles',
            count: 4,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2014',
            label: 'Epidemiology Articles',
            count: 4,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2013',
            label: 'Epidemiology Articles',
            count: 3,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2012',
            label: 'Epidemiology Articles',
            count: 1,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2011',
            label: 'Epidemiology Articles',
            count: 1,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2010',
            label: 'Epidemiology Articles',
            count: 1,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2007',
            label: 'Epidemiology Articles',
            count: 1,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2006',
            label: 'Epidemiology Articles',
            count: 1,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2000',
            label: 'Epidemiology Articles',
            count: 1,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1996',
            label: 'Epidemiology Articles',
            count: 1,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1991',
            label: 'Epidemiology Articles',
            count: 2,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1990',
            label: 'Epidemiology Articles',
            count: 1,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2024',
            label: 'Non Epidemiology Articles',
            count: 1604,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2023',
            label: 'Non Epidemiology Articles',
            count: 6954,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2022',
            label: 'Non Epidemiology Articles',
            count: 7442,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2021',
            label: 'Non Epidemiology Articles',
            count: 7457,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2020',
            label: 'Non Epidemiology Articles',
            count: 6951,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2019',
            label: 'Non Epidemiology Articles',
            count: 5941,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2018',
            label: 'Non Epidemiology Articles',
            count: 5482,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2017',
            label: 'Non Epidemiology Articles',
            count: 5105,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2016',
            label: 'Non Epidemiology Articles',
            count: 4449,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2015',
            label: 'Non Epidemiology Articles',
            count: 3077,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2014',
            label: 'Non Epidemiology Articles',
            count: 3110,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2013',
            label: 'Non Epidemiology Articles',
            count: 3434,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2012',
            label: 'Non Epidemiology Articles',
            count: 2924,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2011',
            label: 'Non Epidemiology Articles',
            count: 2608,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2010',
            label: 'Non Epidemiology Articles',
            count: 2310,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2009',
            label: 'Non Epidemiology Articles',
            count: 2094,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2008',
            label: 'Non Epidemiology Articles',
            count: 1783,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2007',
            label: 'Non Epidemiology Articles',
            count: 1810,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2006',
            label: 'Non Epidemiology Articles',
            count: 1703,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2005',
            label: 'Non Epidemiology Articles',
            count: 1653,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2004',
            label: 'Non Epidemiology Articles',
            count: 1463,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2003',
            label: 'Non Epidemiology Articles',
            count: 1288,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2002',
            label: 'Non Epidemiology Articles',
            count: 1126,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2001',
            label: 'Non Epidemiology Articles',
            count: 1098,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2000',
            label: 'Non Epidemiology Articles',
            count: 975,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1999',
            label: 'Non Epidemiology Articles',
            count: 822,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1998',
            label: 'Non Epidemiology Articles',
            count: 765,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1997',
            label: 'Non Epidemiology Articles',
            count: 777,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1996',
            label: 'Non Epidemiology Articles',
            count: 735,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1995',
            label: 'Non Epidemiology Articles',
            count: 676,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1994',
            label: 'Non Epidemiology Articles',
            count: 675,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1993',
            label: 'Non Epidemiology Articles',
            count: 543,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1992',
            label: 'Non Epidemiology Articles',
            count: 508,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1991',
            label: 'Non Epidemiology Articles',
            count: 426,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1990',
            label: 'Non Epidemiology Articles',
            count: 414,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1989',
            label: 'Non Epidemiology Articles',
            count: 370,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1988',
            label: 'Non Epidemiology Articles',
            count: 325,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1987',
            label: 'Non Epidemiology Articles',
            count: 268,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1986',
            label: 'Non Epidemiology Articles',
            count: 242,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1985',
            label: 'Non Epidemiology Articles',
            count: 211,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1984',
            label: 'Non Epidemiology Articles',
            count: 119,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1983',
            label: 'Non Epidemiology Articles',
            count: 68,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1982',
            label: 'Non Epidemiology Articles',
            count: 58,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1981',
            label: 'Non Epidemiology Articles',
            count: 53,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1980',
            label: 'Non Epidemiology Articles',
            count: 21,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1979',
            label: 'Non Epidemiology Articles',
            count: 15,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1978',
            label: 'Non Epidemiology Articles',
            count: 9,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1977',
            label: 'Non Epidemiology Articles',
            count: 3,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1976',
            label: 'Non Epidemiology Articles',
            count: 5,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1975',
            label: 'Non Epidemiology Articles',
            count: 2,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '',
            label: 'Non Epidemiology Articles',
            count: 4,
            selected: false,
            __typename: 'FilterCount',
          },
        ],
      },
      {
        label: 'Epidemiology Articles by Year',
        parent: 'epiArticles',
        filterable: true,
        page: 1,
        values: [
          {
            term: '2023',
            label: 'year',
            count: 9,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2022',
            label: 'year',
            count: 44,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2021',
            label: 'year',
            count: 41,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2020',
            label: 'year',
            count: 18,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2019',
            label: 'year',
            count: 10,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2018',
            label: 'year',
            count: 6,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2017',
            label: 'year',
            count: 5,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2016',
            label: 'year',
            count: 3,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2015',
            label: 'year',
            count: 4,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2014',
            label: 'year',
            count: 4,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2013',
            label: 'year',
            count: 3,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2012',
            label: 'year',
            count: 1,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2011',
            label: 'year',
            count: 1,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2010',
            label: 'year',
            count: 1,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2007',
            label: 'year',
            count: 1,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2006',
            label: 'year',
            count: 1,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2000',
            label: 'year',
            count: 1,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1996',
            label: 'year',
            count: 1,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1991',
            label: 'year',
            count: 2,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1990',
            label: 'year',
            count: 1,
            selected: false,
            __typename: 'FilterCount',
          },
        ],
      },
      {
        label: 'Articles by Year',
        parent: 'articles',
        filterable: true,
        page: 1,
        values: [
          {
            term: '2024',
            label: 'year',
            count: 1604,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2023',
            label: 'year',
            count: 6954,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2022',
            label: 'year',
            count: 7442,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2021',
            label: 'year',
            count: 7457,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2020',
            label: 'year',
            count: 6951,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2019',
            label: 'year',
            count: 5941,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2018',
            label: 'year',
            count: 5482,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2017',
            label: 'year',
            count: 5105,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2016',
            label: 'year',
            count: 4449,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2015',
            label: 'year',
            count: 3077,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2014',
            label: 'year',
            count: 3110,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2013',
            label: 'year',
            count: 3434,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2012',
            label: 'year',
            count: 2924,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2011',
            label: 'year',
            count: 2608,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2010',
            label: 'year',
            count: 2310,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2009',
            label: 'year',
            count: 2094,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2008',
            label: 'year',
            count: 1783,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2007',
            label: 'year',
            count: 1810,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2006',
            label: 'year',
            count: 1703,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2005',
            label: 'year',
            count: 1653,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2004',
            label: 'year',
            count: 1463,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2003',
            label: 'year',
            count: 1288,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2002',
            label: 'year',
            count: 1126,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2001',
            label: 'year',
            count: 1098,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2000',
            label: 'year',
            count: 975,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1999',
            label: 'year',
            count: 822,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1998',
            label: 'year',
            count: 765,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1997',
            label: 'year',
            count: 777,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1996',
            label: 'year',
            count: 735,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1995',
            label: 'year',
            count: 676,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1994',
            label: 'year',
            count: 675,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1993',
            label: 'year',
            count: 543,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1992',
            label: 'year',
            count: 508,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1991',
            label: 'year',
            count: 426,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1990',
            label: 'year',
            count: 414,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1989',
            label: 'year',
            count: 370,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1988',
            label: 'year',
            count: 325,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1987',
            label: 'year',
            count: 268,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1986',
            label: 'year',
            count: 242,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1985',
            label: 'year',
            count: 211,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1984',
            label: 'year',
            count: 119,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1983',
            label: 'year',
            count: 68,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1982',
            label: 'year',
            count: 58,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1981',
            label: 'year',
            count: 53,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1980',
            label: 'year',
            count: 21,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1979',
            label: 'year',
            count: 15,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1978',
            label: 'year',
            count: 9,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1977',
            label: 'year',
            count: 3,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1976',
            label: 'year',
            count: 5,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1975',
            label: 'year',
            count: 2,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '',
            label: 'year',
            count: 4,
            selected: false,
            __typename: 'FilterCount',
          },
        ],
      },
      {
        label: 'Projects Count by Year',
        parent: 'projects',
        filterable: false,
        page: 1,
        values: [
          {
            term: '2021',
            label: 'Project Counts by Year',
            count: 69,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2020',
            label: 'Project Counts by Year',
            count: 52,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2019',
            label: 'Project Counts by Year',
            count: 56,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2018',
            label: 'Project Counts by Year',
            count: 47,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2017',
            label: 'Project Counts by Year',
            count: 35,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2016',
            label: 'Project Counts by Year',
            count: 24,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2015',
            label: 'Project Counts by Year',
            count: 18,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2014',
            label: 'Project Counts by Year',
            count: 23,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2013',
            label: 'Project Counts by Year',
            count: 23,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2012',
            label: 'Project Counts by Year',
            count: 25,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2011',
            label: 'Project Counts by Year',
            count: 25,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2010',
            label: 'Project Counts by Year',
            count: 19,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2009',
            label: 'Project Counts by Year',
            count: 25,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2008',
            label: 'Project Counts by Year',
            count: 20,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2007',
            label: 'Project Counts by Year',
            count: 21,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2006',
            label: 'Project Counts by Year',
            count: 14,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2005',
            label: 'Project Counts by Year',
            count: 17,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2004',
            label: 'Project Counts by Year',
            count: 16,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2003',
            label: 'Project Counts by Year',
            count: 16,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2002',
            label: 'Project Counts by Year',
            count: 28,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2001',
            label: 'Project Counts by Year',
            count: 31,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2000',
            label: 'Project Counts by Year',
            count: 29,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1999',
            label: 'Project Counts by Year',
            count: 33,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1998',
            label: 'Project Counts by Year',
            count: 38,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1997',
            label: 'Project Counts by Year',
            count: 38,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1996',
            label: 'Project Counts by Year',
            count: 17,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1995',
            label: 'Project Counts by Year',
            count: 34,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1994',
            label: 'Project Counts by Year',
            count: 42,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1993',
            label: 'Project Counts by Year',
            count: 35,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1992',
            label: 'Project Counts by Year',
            count: 34,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1991',
            label: 'Project Counts by Year',
            count: 28,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1990',
            label: 'Project Counts by Year',
            count: 26,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1989',
            label: 'Project Counts by Year',
            count: 17,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1988',
            label: 'Project Counts by Year',
            count: 26,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1987',
            label: 'Project Counts by Year',
            count: 24,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1986',
            label: 'Project Counts by Year',
            count: 19,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1985',
            label: 'Project Counts by Year',
            count: 11,
            selected: false,
            __typename: 'FilterCount',
          },
        ],
      },
      {
        label: 'Projects Funding by Year',
        parent: 'projects',
        filterable: false,
        page: 1,
        values: [
          {
            term: '2021',
            label: 'Project Funding by Year',
            count: 40488093,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2020',
            label: 'Project Funding by Year',
            count: 26218748,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2019',
            label: 'Project Funding by Year',
            count: 26466421,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2018',
            label: 'Project Funding by Year',
            count: 20660835,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2017',
            label: 'Project Funding by Year',
            count: 15942556,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2016',
            label: 'Project Funding by Year',
            count: 11123556,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2015',
            label: 'Project Funding by Year',
            count: 7993071,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2014',
            label: 'Project Funding by Year',
            count: 8476054,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2013',
            label: 'Project Funding by Year',
            count: 7550835,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2012',
            label: 'Project Funding by Year',
            count: 12360300,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2011',
            label: 'Project Funding by Year',
            count: 10114034,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2010',
            label: 'Project Funding by Year',
            count: 9884721,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2009',
            label: 'Project Funding by Year',
            count: 11246377,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2008',
            label: 'Project Funding by Year',
            count: 9126070,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2007',
            label: 'Project Funding by Year',
            count: 7609078,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2006',
            label: 'Project Funding by Year',
            count: 4878834,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2005',
            label: 'Project Funding by Year',
            count: 5723255,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2004',
            label: 'Project Funding by Year',
            count: 5453970,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2003',
            label: 'Project Funding by Year',
            count: 6300470,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2002',
            label: 'Project Funding by Year',
            count: 9985528,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2001',
            label: 'Project Funding by Year',
            count: 8886823,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '2000',
            label: 'Project Funding by Year',
            count: 7957043,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1999',
            label: 'Project Funding by Year',
            count: 8675637,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1998',
            label: 'Project Funding by Year',
            count: 11544306,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1997',
            label: 'Project Funding by Year',
            count: 11852878,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1996',
            label: 'Project Funding by Year',
            count: 0,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1995',
            label: 'Project Funding by Year',
            count: 6453460,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1994',
            label: 'Project Funding by Year',
            count: 8186360,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1993',
            label: 'Project Funding by Year',
            count: 6595084,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1992',
            label: 'Project Funding by Year',
            count: 6565079,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1991',
            label: 'Project Funding by Year',
            count: 3123480,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1990',
            label: 'Project Funding by Year',
            count: 3748810,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1989',
            label: 'Project Funding by Year',
            count: 3825248,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1988',
            label: 'Project Funding by Year',
            count: 3485671,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1987',
            label: 'Project Funding by Year',
            count: 1511491,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1986',
            label: 'Project Funding by Year',
            count: 1079274,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: '1985',
            label: 'Project Funding by Year',
            count: 1011650,
            selected: false,
            __typename: 'FilterCount',
          },
        ],
      },
      {
        label: 'Clinical Trials by Status',
        parent: 'trials',
        filterable: true,
        page: 1,
        values: [
          {
            term: 'Completed',
            label: 'OverallStatus',
            count: 175,
            __typename: 'FilterCount',
          },
          {
            term: 'Recruiting',
            label: 'OverallStatus',
            count: 115,
            __typename: 'FilterCount',
          },
          {
            term: 'Terminated',
            label: 'OverallStatus',
            count: 84,
            __typename: 'FilterCount',
          },
          {
            term: 'Unknown status',
            label: 'OverallStatus',
            count: 76,
            __typename: 'FilterCount',
          },
          {
            term: 'Active, not recruiting',
            label: 'OverallStatus',
            count: 67,
            __typename: 'FilterCount',
          },
          {
            term: 'Not yet recruiting',
            label: 'OverallStatus',
            count: 19,
            __typename: 'FilterCount',
          },
          {
            term: 'Withdrawn',
            label: 'OverallStatus',
            count: 17,
            __typename: 'FilterCount',
          },
          {
            term: 'Approved for marketing',
            label: 'OverallStatus',
            count: 2,
            __typename: 'FilterCount',
          },
          {
            term: 'Available',
            label: 'OverallStatus',
            count: 2,
            __typename: 'FilterCount',
          },
          {
            term: 'No longer available',
            label: 'OverallStatus',
            count: 1,
            __typename: 'FilterCount',
          },
          {
            term: 'Suspended',
            label: 'OverallStatus',
            count: 1,
            __typename: 'FilterCount',
          },
          {
            term: 'Enrolling by invitation',
            label: 'OverallStatus',
            count: 1,
            __typename: 'FilterCount',
          },
        ],
      },
      {
        label: 'Clinical Trials by Type',
        parent: 'trials',
        filterable: true,
        page: 1,
        values: [
          {
            term: 'Interventional',
            label: 'StudyType',
            count: 499,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: 'Observational',
            label: 'StudyType',
            count: 56,
            selected: false,
            __typename: 'FilterCount',
          },
          {
            term: 'Expanded Access',
            label: 'StudyType',
            count: 5,
            selected: false,
            __typename: 'FilterCount',
          },
        ],
      },
    ],
    selectedId: 'GARD:0017280',
    page: {
      pageSize: 10,
      pageIndex: 0,
      total: 12004,
    },
    tree: [
      {
        name: 'Rare neurologic disease',
        gardId: 'GARD:0022524',
        childrenCount: 48,
        _childrenCount: {
          low: 48,
          high: 0,
        },
      },
      {
        name: 'Rare genetic disease',
        gardId: 'GARD:0022531',
        childrenCount: 33,
        _childrenCount: {
          low: 33,
          high: 0,
        },
      },
      {
        name: 'Rare developmental defect during embryogenesis',
        gardId: 'GARD:0022513',
        childrenCount: 29,
        _childrenCount: {
          low: 29,
          high: 0,
        },
      },
      {
        name: 'Rare skin disease',
        gardId: 'GARD:0022510',
        childrenCount: 17,
        _childrenCount: {
          low: 17,
          high: 0,
        },
      },
      {
        name: 'Rare endocrine disease',
        gardId: 'GARD:0022521',
        childrenCount: 16,
        _childrenCount: {
          low: 16,
          high: 0,
        },
      },
      {
        name: 'Rare otorhinolaryngologic disease',
        gardId: 'GARD:0022528',
        childrenCount: 16,
        _childrenCount: {
          low: 16,
          high: 0,
        },
      },
      {
        name: 'Rare abdominal surgical disease',
        gardId: 'GARD:0022534',
        childrenCount: 16,
        _childrenCount: {
          low: 16,
          high: 0,
        },
      },
      {
        name: 'Rare hepatic disease',
        gardId: 'GARD:0022506',
        childrenCount: 12,
        _childrenCount: {
          low: 12,
          high: 0,
        },
      },
      {
        name: 'Rare maxillo-facial surgical disease',
        gardId: 'GARD:0022507',
        childrenCount: 11,
        _childrenCount: {
          low: 11,
          high: 0,
        },
      },
      {
        name: 'Rare renal disease',
        gardId: 'GARD:0022512',
        childrenCount: 11,
        _childrenCount: {
          low: 11,
          high: 0,
        },
      },
      {
        name: 'Rare gastroenterologic disease',
        gardId: 'GARD:0022516',
        childrenCount: 9,
        _childrenCount: {
          low: 9,
          high: 0,
        },
      },
      {
        name: 'Rare hematologic disease',
        gardId: 'GARD:0022522',
        childrenCount: 9,
        _childrenCount: {
          low: 9,
          high: 0,
        },
      },
      {
        name: 'Rare bone disease',
        gardId: 'GARD:0022511',
        childrenCount: 8,
        _childrenCount: {
          low: 8,
          high: 0,
        },
      },
      {
        name: 'Rare gynecologic or obstetric disease',
        gardId: 'GARD:0022514',
        childrenCount: 8,
        _childrenCount: {
          low: 8,
          high: 0,
        },
      },
      {
        name: 'Rare respiratory disease',
        gardId: 'GARD:0022517',
        childrenCount: 8,
        _childrenCount: {
          low: 8,
          high: 0,
        },
      },
      {
        name: 'Rare urogenital disease',
        gardId: 'GARD:0022532',
        childrenCount: 8,
        _childrenCount: {
          low: 8,
          high: 0,
        },
      },
      {
        name: 'Rare disorder potentially indicated for transplant or complication after transplantation',
        gardId: 'GARD:0022536',
        childrenCount: 8,
        _childrenCount: {
          low: 8,
          high: 0,
        },
      },
      {
        name: 'Rare cardiac disease',
        gardId: 'GARD:0022515',
        childrenCount: 7,
        _childrenCount: {
          low: 7,
          high: 0,
        },
      },
      {
        name: 'Rare immune disease',
        gardId: 'GARD:0022523',
        childrenCount: 7,
        _childrenCount: {
          low: 7,
          high: 0,
        },
      },
      {
        name: 'Rare surgical thoracic disease',
        gardId: 'GARD:0022518',
        childrenCount: 6,
        _childrenCount: {
          low: 6,
          high: 0,
        },
      },
      {
        name: 'Rare infectious disease',
        gardId: 'GARD:0022509',
        childrenCount: 5,
        _childrenCount: {
          low: 5,
          high: 0,
        },
      },
      {
        name: 'Rare to-be-classified GARD Diseases',
        gardId: 'GARD:0030000',
        childrenCount: 5,
        _childrenCount: {
          low: 5,
          high: 0,
        },
      },
      {
        name: 'Rare ophthalmic disorder',
        gardId: 'GARD:0022520',
        childrenCount: 4,
        _childrenCount: {
          low: 4,
          high: 0,
        },
      },
      {
        name: 'Rare systemic or rheumatologic disease',
        gardId: 'GARD:0022525',
        childrenCount: 4,
        _childrenCount: {
          low: 4,
          high: 0,
        },
      },
      {
        name: 'Rare odontologic disease',
        gardId: 'GARD:0022526',
        childrenCount: 4,
        _childrenCount: {
          low: 4,
          high: 0,
        },
      },
      {
        name: 'Rare allergic disease',
        gardId: 'GARD:0022530',
        childrenCount: 4,
        _childrenCount: {
          low: 4,
          high: 0,
        },
      },
      {
        name: 'Rare disorder due to toxic effects',
        gardId: 'GARD:0022533',
        childrenCount: 4,
        _childrenCount: {
          low: 4,
          high: 0,
        },
      },
      {
        name: 'Rare systemic or rheumatological disease of childhood',
        gardId: 'GARD:0021079',
        childrenCount: 3,
        _childrenCount: {
          low: 3,
          high: 0,
        },
      },
      {
        name: 'Rare circulatory system disease',
        gardId: 'GARD:0022527',
        childrenCount: 3,
        _childrenCount: {
          low: 3,
          high: 0,
        },
      },
      {
        name: 'Rare infertility',
        gardId: 'GARD:0022529',
        childrenCount: 2,
        _childrenCount: {
          low: 2,
          high: 0,
        },
      },
      {
        name: 'Rare neoplastic disease',
        gardId: 'GARD:0022535',
        childrenCount: 2,
        _childrenCount: {
          low: 2,
          high: 0,
        },
      },
    ],
  },
};
